### PR TITLE
Fix strict proto

### PR DESCRIPTION
**Pull request by victorapm**
Copied from #773.

`-Wstrict-prototypes` is a warning for functions declared or defined without specified argument types. The changes in this PR make the code clean for this warning.

### CODE REVIEW

**Review by ulrikeyang — APPROVED** [review]
This looks fine

**Comment by prj-** [comment]
Could I help in any way get things moving?

**Comment by prj-** [comment]
Any update @victorapm?

**Comment by victorapm** [comment]
@prj- I will merge this into master after @liruipeng finishes his review

**Review by liruipeng — APPROVED** [review]
looks good to me. Thanks!

**Review by liruipeng — APPROVED** [review]
Looks good to me. I think we need to remember writing `func_name(void)` for functions that don't even have arguments.

**Comment by victorapm** [comment]
@rfalgout I ran `astyle-apply.sh` and noticed that it removes a few `(void)` added in this PR, e.g.:

```diff
-hypre_MemoryTracker* hypre_memory_tracker(void); 
-hypre_MemoryTracker * hypre_MemoryTrackerCreate(void);
+hypre_MemoryTracker* hypre_memory_tracker();
+hypre_MemoryTracker * hypre_MemoryTrackerCreate();
```

So I didn't commit the changes yet. Do you know the reason why or how to avoid this? Thanks!

**Comment by rfalgout** [comment]
> @rfalgout I ran `astyle-apply.sh` and noticed that it removes a few `(void)` added in this PR, e.g.:
> 
> ```diff
> -hypre_MemoryTracker* hypre_memory_tracker(void); 
> -hypre_MemoryTracker * hypre_MemoryTrackerCreate(void);
> +hypre_MemoryTracker* hypre_memory_tracker();
> +hypre_MemoryTracker * hypre_MemoryTrackerCreate();
> ```
> 
> So I didn't commit the changes yet. Do you know the reason why or how to avoid this? Thanks!

Hi @victorapm .  I was unable to replicate this on my macbook with version 3.1 of astyle.  Which version are you using?

I created a simple C file with three prototypes at the top (before `main`):
```
int test1(void);
void test2(void);
void test3();
```
None of them were changed.  Let me know.  Thanks!

**Comment by victorapm** [comment]
@rfalgout It turned out that some `(void)` were not being used in `protos.h`, so the script was removing some `(void)` occurrences because of that instead of `astyle` itself. I fixed this and reran `apply-astyle.sh`, everything is working properly now.

> we need to remember writing func_name(void)

@liruipeng, following your concern, I added `-Wstrict-prototypes` to `machine-tux`, so that it gets tested

https://github.com/hypre-space/hypre/blob/de08c4e132f2e6441f6d9aeb21d6e4fec7993811/AUTOTEST/machine-tux.sh#L99-L101

**Review by rfalgout — APPROVED** [review]
Looks good.  Thanks!

**Comment by victorapm** [comment]
@prj- just letting you know about this merge. Thanks for your contribution!

**Comment by prj-** [comment]
Thank you for shepherding the PR.

**Pull request merged**
