### PR TITLE
Rl gpu

### PR DESCRIPTION
**Pull request by liruipeng**
1. GPU FFFC code. Wrote it using thrust, without writing any raw cuda kernels. Somewhat complicated but it will be directly portable to AMD GPUs. May consider more in this line of future development
2. Optimize CPU FFFC, so should produce the same matrices as by the GPU code
3. Make minor changes in the SoC matrix from the device function that generates 
4. Minor cosmetic format changes

### CODE REVIEW

**Review by rfalgout — APPROVED** [review]
There's no way for me to follow the details of this, but it otherwise looks fine.

**Review by ulrikeyang — APPROVED** [review]
Looks fine

**Review by oseikuffuor1 — APPROVED** [review]
Looks good to me.

**Review by ulrikeyang — APPROVED** [review]
Looks fine to me

**Pull request merged**
