### PR TITLE
Fix recmat SysPFMG solver

### PR DESCRIPTION
**Pull request by rfalgout**
This PR fixes the SysPFMG solver.  It does a number of things:
* Changes SysPFMG to use matmult to create the coarse grid, and to use matvec for interpolation and restriction
* Adds some companion functions for the Agglomerate utility to reduce some code replication
* Extends the PMatrix and PMatmult functionality
* Makes astyle formatting changes

### CODE REVIEW

**Comment by rfalgout** [comment]
Hi @victorapm and @waynemitchell .  Many files have changed here, but a bunch of it involves reorganizing of code (and some astyle changes).  I am running the full set of recmat regression tests to make sure I didn't miss anything, but it should be clean.

I'd like to get this merged possibly today since I'm leaving for vacation tomorrow, but I don't want to rush you either.  This may cause conflicts with what you are working on, but hopefully nothing major or difficult to resolve.

Thanks!

**Comment by rfalgout** [comment]
The `machine-tux-recmat.sh` tests are clean

**Review by victorapm — APPROVED** [review]
Thank you for all the nice changes, Rob!

**Review by waynemitchell — APPROVED** [review]
Looks good to me. I made some adjustments to your changes to some of the boxloops that I had written, which you can double check again.

**Pull request merged**
