### PR TITLE
fix with umpire 2022

### PR DESCRIPTION
**Pull request by liruipeng**
This PR fixes hypre with umpire 2022

### CODE REVIEW

**Comment by liruipeng** [comment]
Hi @davidbeckingsale, Can you please take a look at this PR? We wanted to upgrade to the latest Umpire. Thanks!

**Comment by davidbeckingsale** [comment]
Looks good!

**Comment by liruipeng** [comment]
@davidbeckingsale Thank you!

**Review by rfalgout — APPROVED** [review]
Looks good.  Thanks!

**Pull request merged**
