### PR TITLE
Fix headers

### PR DESCRIPTION
**Pull request by rfalgout**
This fixes (hopefully) the header file usage problems mentioned in issues #126 and #84:

- Removed lower-case header dependencies in examples
- Fixed improper inclusion of _hypre_utilities.h in user header files
- Added a 'check-headers.sh' regression test that compiles the examples with options that output header file inclusion information, then checks to see if any internal header files were used
- Moved HYPRE_Init() to 'HYPRE_utilities.h'

### CODE REVIEW

**Comment by rfalgout** [comment]
One more thing...  I removed the lobpcg run (ex11) from the default examples test.  This should make it possible to add example testing to the spack autotest script.

**Comment by stefanozampini** [comment]
I have just tried the branch, and we still have some issues with PETSc and HYPRE-GPU. 
PETSc source code is not compiled with nvcc and we make use of `hypre_ParVector`, and `hypre_ParCSRMatrix` inside the library code, as well as the struct and sstruct API. Below is a list of compilation errors 

```
zampins@vulture:~/Devel/petsc$ make -f gmakefile libs -i
          CC arch-gpu-double/obj/vec/vec/impls/hypre/vhyp.o
In file included from /opt/ecrc/cuda/10.2/include/thrust/detail/config.h:22:0,
                 from /opt/ecrc/cuda/10.2/include/thrust/execution_policy.h:23,
                 from /home/zampins/Devel/hypre/myinstall/include/_hypre_utilities.h:1215,
                 from /home/zampins/Devel/hypre/myinstall/include/_hypre_IJ_mv.h:14,
                 from /home/zampins/Devel/petsc/include/../src/vec/vec/impls/hypre/vhyp.h:6,
                 from /home/zampins/Devel/petsc/src/vec/vec/impls/hypre/vhyp.c:7:
/opt/ecrc/cuda/10.2/include/thrust/version.h:83:1: error: unknown type name ‘namespace’
 namespace thrust
 ^
/opt/ecrc/cuda/10.2/include/thrust/version.h:84:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
In file included from /opt/ecrc/cuda/10.2/include/thrust/detail/config/config.h:28:0,
                 from /opt/ecrc/cuda/10.2/include/thrust/detail/config.h:23,
                 from /opt/ecrc/cuda/10.2/include/thrust/execution_policy.h:23,
                 from /home/zampins/Devel/hypre/myinstall/include/_hypre_utilities.h:1215,
                 from /home/zampins/Devel/hypre/myinstall/include/_hypre_IJ_mv.h:14,
                 from /home/zampins/Devel/petsc/include/../src/vec/vec/impls/hypre/vhyp.h:6,
                 from /home/zampins/Devel/petsc/src/vec/vec/impls/hypre/vhyp.c:7:
/opt/ecrc/cuda/10.2/include/thrust/detail/config/cpp_compatibility.h:21:19: fatal error: cstddef: No such file or directory
compilation terminated.
gmakefile:163: recipe for target 'arch-gpu-double/obj/vec/vec/impls/hypre/vhyp.o' failed
make: [arch-gpu-double/obj/vec/vec/impls/hypre/vhyp.o] Error 1 (ignored)
          CC arch-gpu-double/obj/mat/impls/hypre/mhypre.o
In file included from /opt/ecrc/cuda/10.2/include/thrust/detail/config.h:22:0,
                 from /opt/ecrc/cuda/10.2/include/thrust/execution_policy.h:23,
                 from /home/zampins/Devel/hypre/myinstall/include/_hypre_utilities.h:1215,
                 from /home/zampins/Devel/hypre/myinstall/include/_hypre_parcsr_mv.h:9,
                 from /home/zampins/Devel/petsc/include/petscmathypre.h:5,
                 from /home/zampins/Devel/petsc/src/mat/impls/hypre/mhypre.c:8:
/opt/ecrc/cuda/10.2/include/thrust/version.h:83:1: error: unknown type name ‘namespace’
 namespace thrust
 ^
/opt/ecrc/cuda/10.2/include/thrust/version.h:84:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
In file included from /opt/ecrc/cuda/10.2/include/thrust/detail/config/config.h:28:0,
                 from /opt/ecrc/cuda/10.2/include/thrust/detail/config.h:23,
                 from /opt/ecrc/cuda/10.2/include/thrust/execution_policy.h:23,
                 from /home/zampins/Devel/hypre/myinstall/include/_hypre_utilities.h:1215,
                 from /home/zampins/Devel/hypre/myinstall/include/_hypre_parcsr_mv.h:9,
                 from /home/zampins/Devel/petsc/include/petscmathypre.h:5,
                 from /home/zampins/Devel/petsc/src/mat/impls/hypre/mhypre.c:8:
/opt/ecrc/cuda/10.2/include/thrust/detail/config/cpp_compatibility.h:21:19: fatal error: cstddef: No such file or directory
compilation terminated.
gmakefile:163: recipe for target 'arch-gpu-double/obj/mat/impls/hypre/mhypre.o' failed
make: [arch-gpu-double/obj/mat/impls/hypre/mhypre.o] Error 1 (ignored)
          CC arch-gpu-double/obj/dm/impls/da/hypre/mhyp.o
In file included from /opt/ecrc/cuda/10.2/include/thrust/detail/config.h:22:0,
                 from /opt/ecrc/cuda/10.2/include/thrust/execution_policy.h:23,
                 from /home/zampins/Devel/hypre/myinstall/include/_hypre_utilities.h:1215,
                 from /home/zampins/Devel/hypre/myinstall/include/_hypre_struct_mv.h:13,
                 from /home/zampins/Devel/petsc/include/../src/dm/impls/da/hypre/mhyp.h:8,
                 from /home/zampins/Devel/petsc/src/dm/impls/da/hypre/mhyp.c:9:
/opt/ecrc/cuda/10.2/include/thrust/version.h:83:1: error: unknown type name ‘namespace’
 namespace thrust
 ^
/opt/ecrc/cuda/10.2/include/thrust/version.h:84:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
In file included from /opt/ecrc/cuda/10.2/include/thrust/detail/config/config.h:28:0,
                 from /opt/ecrc/cuda/10.2/include/thrust/detail/config.h:23,
                 from /opt/ecrc/cuda/10.2/include/thrust/execution_policy.h:23,
                 from /home/zampins/Devel/hypre/myinstall/include/_hypre_utilities.h:1215,
                 from /home/zampins/Devel/hypre/myinstall/include/_hypre_struct_mv.h:13,
                 from /home/zampins/Devel/petsc/include/../src/dm/impls/da/hypre/mhyp.h:8,
                 from /home/zampins/Devel/petsc/src/dm/impls/da/hypre/mhyp.c:9:
/opt/ecrc/cuda/10.2/include/thrust/detail/config/cpp_compatibility.h:21:19: fatal error: cstddef: No such file or directory
compilation terminated.
gmakefile:163: recipe for target 'arch-gpu-double/obj/dm/impls/da/hypre/mhyp.o' failed
make: [arch-gpu-double/obj/dm/impls/da/hypre/mhyp.o] Error 1 (ignored)
          CC arch-gpu-double/obj/ksp/pc/impls/hypre/hypre.o
In file included from /opt/ecrc/cuda/10.2/include/thrust/detail/config.h:22:0,
                 from /opt/ecrc/cuda/10.2/include/thrust/execution_policy.h:23,
                 from /home/zampins/Devel/hypre/myinstall/include/_hypre_utilities.h:1215,
                 from /home/zampins/Devel/hypre/myinstall/include/_hypre_IJ_mv.h:14,
                 from /home/zampins/Devel/petsc/include/../src/vec/vec/impls/hypre/vhyp.h:6,
                 from /home/zampins/Devel/petsc/src/ksp/pc/impls/hypre/hypre.c:10:
/opt/ecrc/cuda/10.2/include/thrust/version.h:83:1: error: unknown type name ‘namespace’
 namespace thrust
 ^
/opt/ecrc/cuda/10.2/include/thrust/version.h:84:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
In file included from /opt/ecrc/cuda/10.2/include/thrust/detail/config/config.h:28:0,
                 from /opt/ecrc/cuda/10.2/include/thrust/detail/config.h:23,
                 from /opt/ecrc/cuda/10.2/include/thrust/execution_policy.h:23,
                 from /home/zampins/Devel/hypre/myinstall/include/_hypre_utilities.h:1215,
                 from /home/zampins/Devel/hypre/myinstall/include/_hypre_IJ_mv.h:14,
                 from /home/zampins/Devel/petsc/include/../src/vec/vec/impls/hypre/vhyp.h:6,
                 from /home/zampins/Devel/petsc/src/ksp/pc/impls/hypre/hypre.c:10:
/opt/ecrc/cuda/10.2/include/thrust/detail/config/cpp_compatibility.h:21:19: fatal error: cstddef: No such file or directory
compilation terminated.
gmakefile:163: recipe for target 'arch-gpu-double/obj/ksp/pc/impls/hypre/hypre.o' failed
make: [arch-gpu-double/obj/ksp/pc/impls/hypre/hypre.o] Error 1 (ignored)
     CLINKER arch-gpu-double/lib/libpetsc.so.3.013.2
gcc: error: arch-gpu-double/obj/vec/vec/impls/hypre/vhyp.o: No such file or directory
gcc: error: arch-gpu-double/obj/mat/impls/hypre/mhypre.o: No such file or directory
gcc: error: arch-gpu-double/obj/dm/impls/da/hypre/mhyp.o: No such file or directory
gcc: error: arch-gpu-double/obj/ksp/pc/impls/hypre/hypre.o: No such file or directory
gmakefile:99: recipe for target 'arch-gpu-double/lib/libpetsc.so.3.013.2' failed
make: [arch-gpu-double/lib/libpetsc.so.3.013.2] Error 1 (ignored)

```

**Comment by liruipeng** [comment]
@rfalgout if Petsc includes `_hypre_IJ_mv.h` in their code, which includes `_hypre_utilities.h`, the C++ CUDA stuff is exposed. One cannot compile with C compiler. Is it possible to circumvent it?

**Comment by rfalgout** [comment]
I didn't notice @stefanozampini comment above until just now.  It answers my last question.  Sorry about that.  I'll need to think about how we can move forward on this.

**Comment by rfalgout** [comment]
Hi @stefanozampini .  I just spoke with @liruipeng about this, and we are exploring a possible solution to the PETSc include file issue.  We'll get back to you on that, hopefully soon.

**Comment by rfalgout** [comment]
Hi @liruipeng @oseikuffuor1 @ulrikeyang @victorapm .  We are going to merge this pull request before Ruipeng's #128 and fix the PETSc issue separately.  So, when you get a chance, please take a quick look and approve (if okay with it).  Thanks!

**Review by ulrikeyang — APPROVED** [review]
It looks fine, but I didn't check it in detail, I just trust you on that.

**Review by oseikuffuor1 — APPROVED** [review]
Looks good to me. Thanks.

**Review by liruipeng — APPROVED** [review]
Looks good to me. Thanks, Rob!

**Review by victorapm — COMMENTED** [review]
Hi Rob, this looks good for me as well.

**Review by victorapm — APPROVED** [review]

**Pull request merged**
