### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by rfalgout**
This switches the Sphinx documentation style to improve rendering of the "API" pages.  The original `Alabaster` theme did not do a good job of spacing out the function names and descriptions and I could not figure out how to fix that.

There are two themes that work better: `ReadTheDocs` and `Classic`.  The source in this PR currently uses ReadTheDocs, which looks pretty good actually.

Here is the compiled documentation: https://hypre.readthedocs.io/en/update-docs/ (you may need to refresh or clear your browser cache to see the updated pages)

Here it is with the classic theme: https://hypre.readthedocs.io/en/update-docs-classic/

The only thing I customized in the Classic theme was to use left-justified text alignment.  The default is to justify both margins, which looks weird in the API pages.

I added the hypre logo in the ReadTheDocs theme, but used a black-and-white version because it looks better against the blue background.

Let me know what you think.

### CODE REVIEW

**Review by victorapm — APPROVED** [review]
This looks good, Rob! Have you thought about using the Read the Docs sphinx theme instead of classic? https://sphinx-rtd-theme.readthedocs.io/en/stable/

**Comment by rfalgout** [comment]
> This looks good, Rob! Have you thought about using the Read the Docs sphinx theme instead of classic? https://sphinx-rtd-theme.readthedocs.io/en/stable/

Hi @victorapm .  Yes, I did.  But I didn't have it installed on my mac so it was easier to try "classic" first.  I can give it another look.  Thanks!

**Comment by rfalgout** [comment]
Thanks for suggesting the ReadTheDocs theme @victorapm !  I think this looks the best of the 3 but I want to hear what all of you have to say.  I've edited the description at the top of the PR and have pointers to both versions of the updated documentation.  Thanks again!

**Comment by victorapm** [comment]
Nice! I agree this looks better, even though the `Classic` theme was already looking nice. Thanks!

**Comment by rfalgout** [comment]
I just noticed that the compiled version on the read-the-docs page looks a little different from what I see on my mac (it looks better on my mac actually).  Not sure why.  The main thing I notice is that the function names in the "API" are highlighted in blue on my mac instead of grey.  I'll let you know if I make any other changes to fix this.  It may just require a few configuration changes.

**Review by oseikuffuor1 — APPROVED** [review]
Looks good to me too. Thanks Rob.

**Comment by rfalgout** [comment]
Hi All.  After much tinkering with version number requirements, I finally have the read-the-docs version linked to above producing the same pages I get locally on my mac.  So, this is ready to go.  Let me know what you think when you get the chance.  Thanks again!

**Comment by victorapm** [comment]
Thanks, Rob! I can see the difference and it looks good!

**Review by ulrikeyang — APPROVED** [review]
This looks very nice. I like the read the docs version better than the classic version. Thanks for working on this.

**Review by osborn9 — APPROVED** [review]
Looks very nice!

**Comment by waynemitchell** [comment]
Looks great to me! I like the ReadTheDocs theme. I clicked around in here a bit, and I find it's nice and easy to navigate. Thanks, Rob!

**Review by waynemitchell — APPROVED** [review]

**Review by liruipeng — APPROVED** [review]
Looks good to me, though I don't know much about it. Sorry for taking long time to review.

**Pull request merged**
