### PR TITLE
GPU build with raja and kokkos

### PR DESCRIPTION
**Pull request by liruipeng**
This PR fixes hypre's GPU build with raja and kokkos, and adds `machine-lassen-exlibs.sh` for regression tests.

### CODE REVIEW

**Review by rfalgout — APPROVED** [review]
Looks good to me.  Thanks!

**Comment by liruipeng** [comment]
I would like to talk with @rfalgout about how to add `machine-lassen-exlibs.sh` in our monthly GPU tests, which requires installing the libraries.

**Comment by rfalgout** [comment]
> I would like to talk with @rfalgout about how to add `machine-lassen-exlibs.sh` in our monthly GPU tests, which requires installing the libraries.

Hi @liruipeng.  The way we are currently handling external libraries is through spack.  I'm not sure if that can be made to work here, but @osborn9 may be able to help answer that.  Feel free to set up a face-to-face if you want to chat.

**Comment by liruipeng** [comment]
> > I would like to talk with @rfalgout about how to add `machine-lassen-exlibs.sh` in our monthly GPU tests, which requires installing the libraries.
> 
> Hi @liruipeng. The way we are currently handling external libraries is through spack. I'm not sure if that can be made to work here, but @osborn9 may be able to help answer that. Feel free to set up a face-to-face if you want to chat.

OK. Thanks! @rfalgout @osborn9 Let's talk about this in today's team meeting maybe.

**Comment by rfalgout** [comment]
> OK. Thanks! @rfalgout @osborn9 Let's talk about this in today's team meeting maybe.

Good idea.  It's on the agenda!

**Comment by liruipeng** [comment]
I close this PR, since it has been merged into `deviceomp` branch. Will deal everything there.

**Pull request closed without merging**
