### PR TITLE
Softlinks

### PR DESCRIPTION
**Pull request by liruipeng**
This PR (copied from #573) added -f to softlink generation to all the makefiles. After making changes to a source file, one no longer needs to manual delete a subdirectory .so.

### CODE REVIEW

**Comment by liruipeng** [comment]
I am not an expert on this, but it looks fine to me. Thanks @PaulMullowney

**Review by rfalgout — APPROVED** [review]
Looks good to me.

**Review by ulrikeyang — APPROVED** [review]
Looks good. Thanks

**Comment by liruipeng** [comment]
This PR (copied from https://github.com/hypre-space/hypre/pull/573) added -f to softlink generation to all the makefiles.

**Pull request merged**
