### PR TITLE
Improve StructMatrix multiplication

### PR DESCRIPTION
**Pull request by victorapm**
This PR improves the algorithm for multiplying StructMatrices by eliminating comparisons inside BoxLoops.

- [x] Write core functions for computing the product of three coefficients.
- [x] Write core functions for computing the product of two coefficients.
- [x] Group calls to the same multiplication core functions
- [x] Unroll internal loops that are present in BoxLoops used in the multiplication core functions.
- [x] Add regression tests that involve the new core functions added here.

### CODE REVIEW

**Comment by victorapm** [comment]
Results for `RAP` computation with A defined on a single cube and a 7-pt stencil and P with 3-pt stencil. Different sizes for the cube are considered

| Nx  | Ny  | Nz  | DOFs     | Old (23be1e2) | New (1abeb73) |
| --- | --- | --- | -------- | ---- | ---- |
| 128 | 128 | 128 | 2,097,152  | 0.49 | 0.29 |
| 256 | 128 | 128 | 4,194,304  | 0.99 | 0.59 |
| 256 | 256 | 128 | 8,388,608  | 1.98 | 1.19 |
| 256 | 256 | 256 | 16,777,216 | 3.99 | 2.37 |

**Comment by victorapm** [comment]
Hi all,

I believe the performance changes are finished and these are the latest results for RAP with A coming from a 7pt discretization of a cube, P being a 2-pt interpolation matrix and R=P^T:
| Nx  | Ny  | Nz  | DOFs     | Old e504b83d25e94f598d30f902461b09740027af70  | New  de9b7dd1f6951c02db5a5f2fed0b30f7c1c2879a | ParCSR | New/Old | New/ParCSR |
| --- | --- | --- | -------- | ----- | ----- | ------ | --------------- | ------------------ |
| 128 | 128 | 128 | 2,097,152  | 0.479 | 0.105 | 0.390  | 4.5             | 3.7                |
| 256 | 128 | 128 | 4,194,304  | 0.962 | 0.201 | 0.788  | 4.8             | 3.9                |
| 256 | 256 | 128 | 8,388,608  | 2.027 | 0.386 | 1.565  | 5.3             | 4.1                |
| 256 | 256 | 256 | 16,777,216 | 4.147 | 0.767 | 3.134  | 5.4             | 4.1                |

Next, results for 27pt discretization:
| Nx  | Ny  | Nz  | DOFs     | Old  e504b83d25e94f598d30f902461b09740027af70  | New  de9b7dd1f6951c02db5a5f2fed0b30f7c1c2879a | ParCSR | New/Old | New/ParCSR |
| --- | --- | --- | -------- | ------ | ----- | ------ | ------- | ---------- |
| 128 | 128 | 128 | 2097152  | 1.524  | 0.437 | 1.106  | 3.5     | 2.5        |
| 256 | 128 | 128 | 4194304  | 3.009  | 0.841 | 2.194  | 3.6     | 2.6        |
| 256 | 256 | 128 | 8388608  | 6.271  | 1.665 | 4.394  | 3.8     | 2.6        |
| 256 | 256 | 256 | 16777216 | 12.609 | 3.306 | 8.715  | 3.8     | 2.6        |

Thanks!

**Review by rfalgout — APPROVED** [review]
Looks good, Victor.  Thanks!

**Review by ulrikeyang — APPROVED** [review]
This looks good. Thanks

**Pull request merged**
