### PR TITLE
Amgdd fixes

### PR DESCRIPTION
**Pull request by waynemitchell**
This PR fixes an issue arising for AMG-DD when run with cuda 11. The previous implementation for CF relaxation utilizing cusparse's bsrxmv masked matvec routine is no longer valid in cuda 11, so I have simply removed the masked matvec routine (it was previously only used for AMG-DD CF relaxation scheme). In addition, I added an amgdd.saved.lassen file to serve as a baseline for testing on lassen (and other GPU systems) with other small modifications to testing.

### CODE REVIEW

**Review by rfalgout — APPROVED** [review]
This looks good to me @waynemitchell .  Thanks!

**Review by ulrikeyang — APPROVED** [review]
This looks fine. Thanks

**Review by liruipeng — APPROVED** [review]
Looks good! Thanks, @waynemitchell. Please make sure to run regression tests before merging.

**Comment by rfalgout** [comment]
@waynemitchell .  Another thing you should do before merging is bring the `amgdd_fixes` branch up to date with `master`.  See https://github.com/hypre-space/hypre/wiki/Git-Workflow for more info.  Thanks!

**Comment by waynemitchell** [comment]
> Looks good! Thanks, @waynemitchell. Please make sure to run regression tests before merging.

@liruipeng, should I run full regression tests, i.e. ./machine-lassen.sh, or is it sufficient to just run the ij solvers tests?

**Comment by waynemitchell** [comment]
> > Looks good! Thanks, @waynemitchell. Please make sure to run regression tests before merging.
> 
> @liruipeng, should I run full regression tests, i.e. ./machine-lassen.sh, or is it sufficient to just run the ij solvers tests?

This passes ij tests (and no other code is touched), so I am going ahead with merge. Thanks, everyone!

**Pull request merged**
