### PR TITLE
Add memory usage monitoring functions

### PR DESCRIPTION
**Pull request by victorapm**
This PR adds the functions:

- `hypre_HostMemoryGetUsage`: retrieves CPU RAM stats (VmSize, VmPeak, VmRSS, VmHWM)
- `hypre_UmpireMemoryGetUsage`: retrieves GPU RAM stats via umpire (DevSize, DevPeak, ...)
- `hypre_MemoryPrintUsage`: prints memory usage for stdout
- `HYPRE_MemoryPrintUsage`: public API for calling `hypre_MemoryPrintUsage`

Additionally, a new `log_level` member is added to the `hypre_handle` structure. This member enables users to toggle the memory usage functions on or off. `log_level` can be configured via an environment variable, providing easy and fast access to the new memory monitoring capabilities for both users and developers.

Example usage with hypredrive:

```
$ HYPRE_LOG_LEVEL=1 mpirun -np 4 ./hypredrive examples/ex2.yml

Using HYPRE_DEVELOP_STRING: v2.31.0-11-g5de2c5cee (memory)

Running on 4 MPI ranks
------------------------------------------------------------------------------------
general: 
  use_millisec: on
linear_system: 
  rhs_filename: data/ps3d10pt7/np4/IJ.out.b
  matrix_filename: data/ps3d10pt7/np4/IJ.out.A
solver: 
  pcg: 
    max_iter: 100
    two_norm: yes
    rel_change: no
    print_level: 2
    relative_tol: 1.0e-6
    absolute_tol: 0.0
    residual_tol: 0.0
    conv_fac_tol: 0.0
preconditioner: 
  amg: 
    tolerance: 0.0
    max_iter: 1
    print_level: 1
    interpolation: 
      prolongation_type: extended+i
      restriction_type: p_transpose
      trunc_factor: 0.0
      max_nnz_row: 4
    coarsening: 
      type: pmis
      strong_th: 0.25
      seq_amg_th: 0
      max_coarse_size: 64
      min_coarse_size: 0
      max_levels: 25
      num_functions: 1
      rap2: off
      mod_rap2: on
      keep_transpose: off
      max_row_sum: 0.9
    aggressive: 
      num_levels: 0
      num_paths: 1
      prolongation_type: multipass
      trunc_factor: 0.0
      max_nnz_row: 0
      P12_trunc_factor: 0.0
      P12_max_elements: 0
    relaxation: 
      down_type: forward-hl1gs
      up_type: backward-hl1gs
      coarse_type: ge
      down_sweeps: -1
      up_sweeps: -1
      coarse_sweeps: 1
      num_sweeps: 1
      order: 0
      weight: 1.0
      outer_weight: 1.0
    smoother: 
      type: fsai
      num_levels: 0
      num_sweeps: 1
------------------------------------------------------------------------------------
[0]: hypre_IJMatrixSetValuesParCSR at line 1036 | VmSize/Peak: (12.88 / 12.91) GB | VmRSS/HWM: ( 1.81 /  1.81) GB | Free/Total: (42.32 /  62.71) GB
[1]: hypre_IJMatrixSetValuesParCSR at line 1036 | VmSize/Peak: (12.88 / 12.90) GB | VmRSS/HWM: ( 1.80 /  1.80) GB | Free/Total: (42.32 /  62.71) GB
[2]: hypre_IJMatrixSetValuesParCSR at line 1036 | VmSize/Peak: (12.88 / 12.91) GB | VmRSS/HWM: ( 1.81 /  1.81) GB | Free/Total: (42.32 /  62.71) GB
[3]: hypre_IJMatrixSetValuesParCSR at line 1036 | VmSize/Peak: (12.88 / 12.90) GB | VmRSS/HWM: ( 1.81 /  1.81) GB | Free/Total: (42.32 /  62.71) GB
[0]: hypre_IJMatrixAssembleParCSR at line 2957 | VmSize/Peak: (12.88 / 12.91) GB | VmRSS/HWM: ( 1.81 /  1.81) GB | Free/Total: (42.32 /  62.71) GB
[1]: hypre_IJMatrixAssembleParCSR at line 2957 | VmSize/Peak: (12.88 / 12.90) GB | VmRSS/HWM: ( 1.80 /  1.80) GB | Free/Total: (42.32 /  62.71) GB
[2]: hypre_IJMatrixAssembleParCSR at line 2957 | VmSize/Peak: (12.88 / 12.91) GB | VmRSS/HWM: ( 1.81 /  1.81) GB | Free/Total: (42.32 /  62.71) GB
[3]: hypre_IJMatrixAssembleParCSR at line 2957 | VmSize/Peak: (12.88 / 12.90) GB | VmRSS/HWM: ( 1.81 /  1.81) GB | Free/Total: (42.32 /  62.71) GB
====================================================================================
Solving linear system #0 with 1000 rows and 6400 nonzeros...
[0]: BoomerAMG setup begin | VmSize/Peak: (21.01 / 21.04) GB | VmRSS/HWM: ( 1.81 /  1.81) GB | Free/Total: (42.32 /  62.71) GB | UVmSize/UVmPeak: ( 0.00 /  0.00) GB
[1]: BoomerAMG setup begin | VmSize/Peak: (21.01 / 21.04) GB | VmRSS/HWM: ( 1.80 /  1.80) GB | Free/Total: (42.32 /  62.71) GB | UVmSize/UVmPeak: ( 0.00 /  0.00) GB
[2]: BoomerAMG setup begin | VmSize/Peak: (21.01 / 21.04) GB | VmRSS/HWM: ( 1.81 /  1.81) GB | Free/Total: (42.32 /  62.71) GB | UVmSize/UVmPeak: ( 0.00 /  0.00) GB
[3]: BoomerAMG setup begin | VmSize/Peak: (21.01 / 21.04) GB | VmRSS/HWM: ( 1.81 /  1.81) GB | Free/Total: (42.32 /  62.71) GB | UVmSize/UVmPeak: ( 0.00 /  0.00) GB


 Num MPI tasks = 4

 Num OpenMP threads = 1


BoomerAMG SETUP PARAMETERS:

 Max levels = 25
 Num levels = 3

 Strength Threshold = 0.250000
 Interpolation Truncation Factor = 0.000000
 Maximum Row Sum Threshold for Dependency Weakening = 0.900000

 Coarsening Type = PMIS 
 measures are determined locally


 No global partition option chosen.

 Interpolation = extended+i interpolation

Operator Matrix Information:

             nonzero            entries/row          row sums
lev    rows  entries sparse   min  max     avg      min         max
======================================================================
  0    1000     6400  0.006     4    7     6.4   0.000e+00   3.000e+00
  1     362     7678  0.059     7   43    21.2  -3.234e-15   4.291e+00
  2      60     1994  0.554    17   54    33.2   8.050e-01   5.553e+00


Interpolation Matrix Information:
                    entries/row        min        max            row sums
lev  rows x cols  min  max  avgW     weight      weight       min         max
================================================================================
  0  1000 x 362     1    4   4.0   5.263e-02   4.167e-01   4.000e-01   1.000e+00
  1   362 x 60      1    4   3.9   5.635e-03   5.457e-01   1.308e-01   1.000e+00


     Complexity:   grid = 1.422000
               operator = 2.511250
                 memory = 3.161094




BoomerAMG SOLVER PARAMETERS:

  Maximum number of cycles:         1 
  Stopping Tolerance:               0.000000e+00 
  Cycle type (1 = V, 2 = W, etc.):  1

  Relaxation Parameters:
   Visiting Grid:                     down   up  coarse
            Number of sweeps:            1    1     1 
   Type 0=Jac, 3=hGS, 6=hSGS, 9=GE:     13   14     9 
   Point types, partial sweeps (1=C, -1=F):
                  Pre-CG relaxation (down):   0
                   Post-CG relaxation (up):   0
                             Coarsest grid:   0

[0]: BoomerAMG setup end | VmSize/Peak: (21.08 / 21.08) GB | VmRSS/HWM: ( 1.81 /  1.81) GB | Free/Total: (42.30 /  62.71) GB | UVmSize/UVmPeak: ( 0.00 /  0.00) GB
[1]: BoomerAMG setup end | VmSize/Peak: (21.08 / 21.14) GB | VmRSS/HWM: ( 1.81 /  1.81) GB | Free/Total: (42.30 /  62.71) GB | UVmSize/UVmPeak: ( 0.00 /  0.00) GB
[2]: BoomerAMG setup end | VmSize/Peak: (21.08 / 21.08) GB | VmRSS/HWM: ( 1.81 /  1.81) GB | Free/Total: (42.30 /  62.71) GB | UVmSize/UVmPeak: ( 0.00 /  0.00) GB
[3]: BoomerAMG setup end | VmSize/Peak: (21.08 / 21.14) GB | VmRSS/HWM: ( 1.81 /  1.81) GB | Free/Total: (42.30 /  62.71) GB | UVmSize/UVmPeak: ( 0.00 /  0.00) GB
<b,b>: 1.000000e+03


Iters       ||r||_2     conv.rate  ||r||_2/||b||_2
-----    ------------   ---------  ------------ 
    1    1.064402e+01    0.336593    3.365933e-01
    2    7.508307e-01    0.070540    2.374335e-02
    3    5.602217e-02    0.074614    1.771577e-03
    4    3.965849e-03    0.070791    1.254112e-04
    5    2.628232e-04    0.066272    8.311198e-06
    6    1.756500e-05    0.066832    5.554540e-07


====================================================================================


STATISTICS SUMMARY:

+------------+-------------+-------------+-------------+-------------+-------------+
|            |    LS build |       setup |       solve |    relative |             |
|      Entry |  times [ms] |  times [ms] |  times [ms] |   res. norm |       iters |
+------------+-------------+-------------+-------------+-------------+-------------+
|          0 |       4.132 |     282.530 |     234.172 |    5.55e-07 |           6 |
+------------+-------------+-------------+-------------+-------------+-------------+
```

### CODE REVIEW

**Review by oseikuffuor1 — APPROVED** [review]

**Comment by rfalgout** [comment]
Hi @victorapm .  How is this turned on and off?  Through a configuration option?  Aside from this question, the code looks good to me.  Let me know.  Thanks!

**Comment by victorapm** [comment]
Hi Rob, the messages are turned off/on via the environment variable `HYPRE_LOG_LEVEL`:

- `0`: no messaging and therefore no system level queries about memory usage.
- `1`: check memory usage per rank and display it.
- `2`: check memory usage per rank, compute aggregate statistics and display them.

We chose to use an environment variable to make this functionality easy to toggle without requiring changes to user code. Please let me know your thoughts!

**Comment by rfalgout** [comment]
Okay, now I see where this happens.  We've never used environment variables to control the way hypre behaves.  I'm not sure it's a path we should go down.  Why not define a hypre handle routine to set this (e.g., like HYPRE_SetUseGpuRand)?  The user's driver code could then control things via an environment variable (if preferred) that they 'getenv' and pass to hypre through this function.  Once the code is written the first time, no user code changes are required, right?  In addition, users could choose to control this functionality in other ways such as on the command line or through an input file, etc.

Let me know if I am missing something here.  Thanks!

**Comment by victorapm** [comment]
Sure, this idea sounds good to me and I can make the changes. Thanks!

**Comment by liruipeng** [comment]
Is it possible to connect this with the memory tracker, which also reports total/peak, and also tries detects leaks?

**Comment by victorapm** [comment]
Rui Peng, you mean turning on the memory tracker according to the value passed to the log level?

**Comment by liruipeng** [comment]
> Rui Peng, you mean turning on the memory tracker according to the value passed to the log level?

No. I was just wondering if the memory stats (peak, total) could be gotten from the tracker. For sure one needs to turn on the tracker at the configure time.

**Comment by victorapm** [comment]
I see now. The issue with the tracker is that it can use a lot of memory. I couldn't get it to work in some cases (app code would crash due to lack of free ram). I think the solution in this PR is good because it simply relies on system calls

**Comment by liruipeng** [comment]
OK. I guess I need to understand how it works. Where is `/proc/self/status` from? Is this for Linux only?

**Comment by victorapm** [comment]
It's Linux and MacOS only, so no windows support here. `self` is a shortcut to the current `pid` and `/proc/self/status` gives you info about RAM and other stuff

**Comment by liruipeng** [comment]
> I see now. The issue with the tracker is that it can use a lot of memory. I couldn't get it to work in some cases (app code would crash due to lack of free ram). I think the solution in this PR is good because it simply relies on system calls

That's true since it is not an efficient implementation, where store every memory transition (alloc, copy, free) in text format. If the app runs long enough, it will OOM.

**Comment by victorapm** [comment]
We could think of improving it... It's quite nice tool...

**Comment by liruipeng** [comment]
> We could think of improving it... It's quite nice tool...

Yep, at some point, but that's a different topic. 

I didn't know those system calls, which seem very neat though. The PR generally looks good to me.

**Comment by victorapm** [comment]
Hi all, I've removed `getenv`, added hypre functions for setting `log_level`, and added documentation

**Review by rfalgout — APPROVED** [review]
Looks good to me.  Thanks!

**Pull request merged**
