### PR TITLE
Release 2.31.0

### PR DESCRIPTION
**Pull request by rfalgout**
See issue #1067 .

### CODE REVIEW

**Comment by rfalgout** [comment]
@victorapm I am having issues with the `tail +7` command in `seq_block_mv/headers`.  The `_hypre*.h` files are supposed to basically behave as if we did `#include file.h` directly in the source, but we do it this way to minimize the number of header files to install.  Why do you not want to `cat` the entire two files?

**Comment by victorapm** [comment]
Hi Rob, I do `tail +7` to exclude the headers (didn't want to include the copyright header multiple times in the `_hypre` file)

What was the issue exactly?

If it turns out time-consuming, I would say let's just do `cat`

**Comment by rfalgout** [comment]
I get these error messages when I run `headers` on my tux box:
```
tail: cannot open ‘+7’ for reading: No such file or directory
tail: cannot open ‘+7’ for reading: No such file or directory
```
This came up because the `config/astyle-apply.sh` script also runs the `headers` scripts.  I noticed differences between my tux box and my mac (which doesn't complain).

**Review by victorapm — APPROVED** [review]
Thanks!

**Review by liruipeng — APPROVED** [review]

**Review by oseikuffuor1 — APPROVED** [review]
Thanks!

**Comment by rfalgout** [comment]
@waynemitchell Does this release look good to you?

**Review by waynemitchell — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
