### PR TITLE
Fixes for Cray compiler

### PR DESCRIPTION
**Pull request by bavier**
These changes allow hypre to build out-of-the-box with Cray's C compiler.

### CODE REVIEW

**Comment by liruipeng** [comment]
This looks good to me. One question for `__builtin_ffs`: I suppose it is a GNU built-in function. How portable is it? Apparently, it works for Cray. How about others like Intel. Thanks!

**Comment by bavier** [comment]
The Cray compiler has a problem with `__builtin_ffs`, but Intel and Clang compilers support it, afaik.  The benefit of `ffs()` is that it is a POSIX-defined function.

**Comment by liruipeng** [comment]
> The Cray compiler has a problem with `__builtin_ffs`, but Intel and Clang compilers support it, afaik. The benefit of `ffs()` is that it is a POSIX-defined function.

Yes, right. I misread. You changed `__builtin_ffs` to `ffs()` not the other way around. This makes more sense. Thanks!

**Comment by liruipeng** [comment]
@bavier The regression tests on our side seem clean. Can you please run tests on your side again before we merge the PR? Thanks!

-Ruipeng

**Comment by bavier** [comment]
I was able to successfully build and run `make  check` with the 2 commits you made.

**Comment by liruipeng** [comment]
@rfalgout @ulrikeyang Can you please review this PR? It looks good for me. Thanks!

**Review by rfalgout — APPROVED** [review]
Looks good to me!

**Review by ulrikeyang — APPROVED** [review]

**Pull request merged**
