### PR TITLE
Release 2.27.0

### PR DESCRIPTION
**Pull request by rfalgout**
See Issue #800

### CODE REVIEW

**Review by victorapm — APPROVED** [review]

**Review by liruipeng — APPROVED** [review]
Looks good. Thank you!

**Review by ulrikeyang — APPROVED** [review]
Looks good. Thanks

**Comment by prj-** [comment]
Naive question, but are there no plans to get https://github.com/hypre-space/hypre/pull/765 merged before this release? This will effectively make 2.27.0 unusable with modern enough Intel compilers 😢 This also means that PETSc 3.19.0 (scheduled for a March release) won't ship a functioning _hypre_ version (unless you release 2.27.1 or 2.28.0 in the meantime, of course).

**Comment by rfalgout** [comment]
> Naive question, but are there no plans to get #765 merged before this release? This will effectively make 2.27.0 unusable with modern enough Intel compilers 😢 This also means that PETSc 3.19.0 (scheduled for a March release) won't ship a functioning _hypre_ version (unless you release 2.27.1 or 2.28.0 in the meantime, of course).

PR #765 will take more time before merging.  I am uneasy about it for a number of reasons, highest on the list being that it may break our user's build systems here at LLNL.  Normally an update of autoconf should be trivial for us since we only use it to create the `configure` script.  This one is not, mainly because it defines the compiler (e.g., `CC`) to be a compiler-with-a-compiler-option (e.g., `-std=gnu11`).

**Review by osborn9 — APPROVED** [review]

**Review by oseikuffuor1 — APPROVED** [review]

**Pull request merged**
