### PR TITLE
Adding a new HYPRE_RELEASE_NUMBER macro

### PR DESCRIPTION
**Pull request by rfalgout**
The HYPRE_RELEASE_NUMBER macro in `HYPRE_config.h` is an integer representation of the release that can be compared numerically at compile time against other releases in user build systems.  Other changes include:

- Added `config/version.sh` that should be modified to create new releases
- Renamed the `config/bootstrap` script to `config/update.sh`

### CODE REVIEW

**Review by liruipeng — APPROVED** [review]
Looks good to me. Thanks, @rfalgout

**Review by victorapm — APPROVED** [review]
Looks good. Thanks, Rob!

**Comment by liruipeng** [comment]
@rfalgout From now on, shall we run `./config/update.sh` after changing `configure.in` (as `bootstrap` before)?

**Comment by rfalgout** [comment]
Yes.  I will update the Wiki after the merge is done.

**Review by ulrikeyang — APPROVED** [review]
This looks good. Thanks

**Review by oseikuffuor1 — APPROVED** [review]
Looks great. I like the change from bootstrap to update.

Thanks.

**Comment by rfalgout** [comment]
FYI, when you run `config/update.sh` in the future, you will now always get a message about the release number being either less than, greater than, or the same as the current version.  This should help to prevent mistakes like setting a new release number that is smaller than a previous one, or forgetting to update the release number altogether for a release.

I think it would be smart to have a regression test as well that checks the value of HYPRE_RELEASE_NUMBER relative to the previous release, but I'm not sure how best to implement that.  Let me know if you have any great ideas.

**Review by osborn9 — APPROVED** [review]

**Pull request merged**
