### PR TITLE
Update `error.saved` file

### PR DESCRIPTION
**Pull request by victorapm**
Update `error.saved` file after recent Wextra PR

### CODE REVIEW

**Review by rfalgout — APPROVED** [review]
Thanks!

**Comment by liruipeng** [comment]
@victorapm You probably forgot to update `.saved.lassen`?

**Comment by victorapm** [comment]
Yes, I forgot, sorry! Are you merging your BigJ PR soon?

**Comment by liruipeng** [comment]
> Yes, I forgot, sorry! Are you merging your BigJ PR soon?

No problem. Yes, I just did.

**Comment by victorapm** [comment]
Would you be able to fix `.saved.lassen` before merging your intel_gpu_fix PR? @liruipeng

**Comment by liruipeng** [comment]
Sure

**Comment by victorapm** [comment]
Thanks! So I don't need to create a new PR...

**Pull request merged**
