### PR TITLE
CHANGELOG for 2.26.0

### PR DESCRIPTION
**Pull request by liruipeng**
This PR contains the `CHANGELOG` of $\it hypre$ 2.26.0 (#749)

### CODE REVIEW

**Review by victorapm — APPROVED** [review]
Thanks!

**Review by ulrikeyang — APPROVED** [review]
looks good

**Review by rfalgout — APPROVED** [review]
Looks good.  Thanks!

**Review by waynemitchell — APPROVED** [review]
Thanks, Rui Peng! Looks good.

**Pull request merged**
