### PR TITLE
fixed syntax error with --enable-gpu-aware-mpi

### PR DESCRIPTION
**Pull request by liruipeng**
This PR fixes a syntax error with `--enable-gpu-aware-mpi`

### CODE REVIEW

**Review by rfalgout — APPROVED** [review]
Looks good

**Review by ulrikeyang — APPROVED** [review]

**Review by victorapm — COMMENTED** [review]
Thanks, Ruipeng! Should we erase `// TODO RL` in line 415 since it works now?

**Comment by liruipeng** [comment]
> Thanks, Ruipeng! Should we erase `// TODO RL` in line 415 since it works now?

I left that comment there since it is still unclear whether we need to sync. CUDA stream before doing (GPU-)MPI. We may need to revisit it at some time later. Thanks @victorapm

**Review by victorapm — APPROVED** [review]
Thanks for clarifying, Ruipeng!

**Pull request merged**
