### PR TITLE
Fix file `version`

### LINKED ISSUE #723: `version` file in utilities clashes with c++ `<version>`
Newer C++ standards have a `<version>` header. Thus the `version` (bash) file in `utilities` will now collide with this. In particular, whenever dependent libraries (in this case `thrust`) `#include <version>`, either explicitly or implicitly, they are picking up the `version` file in `utilities` instead. The simplest fix is probably to rename `version` to `version.sh`, but it wasn't clear to me if the file was still used at all or not. Pinging @liruipeng @ulrikeyang @rfalgout

### PR DESCRIPTION
**Pull request by liruipeng**
copied from #725 by @pbauman 

> This avoid an #include issue with newer C++ compilers.
> Fixes https://github.com/hypre-space/hypre/issues/723. It might be possible to just remove this file? I'm not entirely sure, but moving to .sh didn't break anything AFAICT. This fix is needed for forthcoming ROCm versions (and I imagine CUDA will need it at some point too as they start to support C++20).

### CODE REVIEW

**Review by ulrikeyang — APPROVED** [review]
I approved this before.

**Comment by rfalgout** [comment]
Hi @tzanio .  Does MFEM use the script `src/utilities/version` in any way?  We are changing the name to `version.sh`.  Thanks!

**Comment by tzanio** [comment]
Nope, we only use the installed version of hypre.

**Review by rfalgout — APPROVED** [review]
I could not find any other use of this script in hypre, so this should be fine.  Thanks!

**Review by pbauman — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
