### PR TITLE
Move utilities/version to utilities/version.sh

### LINKED ISSUE #723: `version` file in utilities clashes with c++ `<version>`
Newer C++ standards have a `<version>` header. Thus the `version` (bash) file in `utilities` will now collide with this. In particular, whenever dependent libraries (in this case `thrust`) `#include <version>`, either explicitly or implicitly, they are picking up the `version` file in `utilities` instead. The simplest fix is probably to rename `version` to `version.sh`, but it wasn't clear to me if the file was still used at all or not. Pinging @liruipeng @ulrikeyang @rfalgout

### PR DESCRIPTION
**Pull request by pbauman**
This avoid an #include issue with newer C++ compilers.

Fixes #723. It might be possible to just remove this file? I'm not entirely sure, but moving to .sh didn't break anything AFAICT. This fix is needed for forthcoming ROCm versions (and I imagine CUDA will need it at some point too as they start to support C++20).

### CODE REVIEW

**Review by ulrikeyang — APPROVED** [review]
This sounds like a good solution to this issue, for which we already had many complaints, to me.

**Comment by rfalgout** [comment]
Hi @pbauman .  Please give issue #513 a quick read to get my take on this.  The entire software community seems to be rolling over and going with the "easy fix", but I think this sets a bad precedent.  Compiler standards have reserved words, but they should not be reserving file names.  This file is used internally by us.  It is not installed anywhere for others to potentially clash with (so we don't prefix it with `hypre_` for example).

Are you having trouble compiling hypre itself?

At some point I may roll over as well, maybe even now, but the whole thing really rankles me.

We would have to change at least one additional file in the `docs` directory.  Also, I think some of our users (e.g., MFEM) may use this script as part of their installation process (to get version information).

**Comment by pbauman** [comment]
Ah, sorry I missed the other issues.

> Are you having trouble compiling hypre itself?

Yes. Compilation of HYPRE itself is failing internally with future ROCm builds. I'll elaborate with details in the issue.

**Comment by pbauman** [comment]
Hi @rfalgout, I went ahead and added to the discussion in #513. TL;DR - I don't see how to avoid this without renaming the `version` file in HYPRE to something other than `version`. This failure will happen with a future version of ROCm (or the current master of rocPRIM/rocThrust).

**Comment by rfalgout** [comment]
We will need to duplicate this on a branch in hypre and make additional changes.  Also, I need to check with the MFEM team and potentially some other users in case they are using this script in their build systems.

**Comment by liruipeng** [comment]
> We will need to duplicate this on a branch in hypre and make additional changes. Also, I need to check with the MFEM team and potentially some other users in case they are using this script in their build systems.

I created another PR from a branch that has merged in this one. https://github.com/hypre-space/hypre/pull/731

**Pull request merged**
