### PR TITLE
PETSc fix

### PR DESCRIPTION
**Pull request by liruipeng**
1. Fixing compile, build issues with CUDA in #151 
2. Fixing a case where Cusparse cannot properly do matvec with m-by-0 matrix
3. Adding a special case for `hypre_SeqVectorScale` with scale = 1.0

### CODE REVIEW

**Review by ulrikeyang — COMMENTED** [review]
What are the changes in the configure files about?

**Comment by liruipeng** [comment]
> What are the changes in the configure files about?

@ulrikeyang 
As reported in #151, in `mpicc -Xcompiler "-fPIC"`, `-Xcompiler`, which is needed by `nvcc`, cannot be recognized by `mpicc`. But `mpixlC` seems fine with it, so the problem did not appear on our side at Ray or Lassen.

**Review by rfalgout — APPROVED** [review]
Looks good to me.  -Rob

**Review by ulrikeyang — APPROVED** [review]

**Comment by liruipeng** [comment]
@rfalgout @ulrikeyang Thank you for reviewing and approving. I had to make a bit more changes after running regression tests, which changed  assertions in matvec  to make it less rigorous (`<=` as opposed to `==`, see https://github.com/hypre-space/hypre/blob/9b5f2730cdd7b6c57b8e38caa294532d234b5435/src/seq_mv/csr_matvec_device.c#L46) and commented. Please take a look if you would like to. Thanks!

**Comment by rfalgout** [comment]
Hi @liruipeng .  These assert changes seem reasonable to me.  Thanks!

**Review by AerysL — APPROVED** [review]
Looks good to me

**Comment by liruipeng** [comment]
Hi All, I made some changes after pulling the master in. @bjorn2 Can you please take a look and I will merge it in. Thanks!

**Comment by rfalgout** [comment]
Hi @liruipeng .  Still looks good to me.  Thanks!

**Review by bjorn2 — APPROVED** [review]

**Pull request merged**
