### PR TITLE
Adding reference manual info to Sphinx documentation

### PR DESCRIPTION
**Pull request by rfalgout**
I finally came up with a reasonable way to add the reference manual to the Sphinx online user documentation.  There is still some cleaning up that we can do in the future, but this is a good step forward.  You can view the new documentation here:

    https://hypre.readthedocs.io/en/docs/index.html

On the left, you will see a new tab called 'API'.  Click on that to browse the reference material.  Some comments:

- This uses a combination of sphinx, doxygen, and breathe.  Basically, the header file stuff we used before with doc++ and more recently with doxygen is being imported into sphinx through an extension called breathe.
- Even though we were already using doxygen before, I had not really worked on the header file comments so that they render more nicely.  You will see lots of (pretty straightforward) changes to the header files because of that.
- I would like to have reference pages that are not so long, but I can't figure out a nice way to do that without adding a bunch of extra files to the usr-manual directory.  I already had to add more than I really wanted to.  Maybe some new features in breathe will become available in the future.

Let me know what you think.  Thanks!

### CODE REVIEW

**Comment by rfalgout** [comment]
BTW, I recommend telling github to "ignore whitespace" when browsing the header files, because I did also do some indentation and format fixing.

**Review by ulrikeyang — APPROVED** [review]
This looks very nice!

**Review by oseikuffuor1 — APPROVED** [review]
Thanks @rfalgout . This looks really nice. Is it straightforward to update this with new information? When the ILU PR is merged, we will need to update it to include that as well.

**Comment by rfalgout** [comment]
Hi @oseikuffuor1 .  I can wait until you and Victor get your pull requests in, then merge and update this one once more.  It's taking more time than I thought it would to get those two requests done, though.  Do you think it will happen soonish?  Thanks!

**Comment by oseikuffuor1** [comment]
@rfalgout Yes, hopefully we can get Victor's merged by the end of the week, then I can merge his into mine. Then it should be ready to merge to master.

**Review by liruipeng — APPROVED** [review]
I don't know much about these, but it looks fine to me. Thanks!

**Comment by rfalgout** [comment]
Hi @liruipeng , @ulrikeyang , @oseikuffuor1 .  I wrote a README file on building the documentation that you can see by navigating to https://github.com/hypre-space/hypre/tree/docs/src/docs.  It would be great if one of you could give this a test drive at some point to see if it works for you.  No rush. 
 Thanks!

**Comment by liruipeng** [comment]
> Hi @liruipeng , @ulrikeyang , @oseikuffuor1 . I wrote a README file on building the documentation that you can see by navigating to https://github.com/hypre-space/hypre/tree/docs/src/docs. It would be great if one of you could give this a test drive at some point to see if it works for you. No rush.
> Thanks!

Hi, @rfalgout I tested it and it worked fine for me. But I did not create a Python virtual environment (venv) since my python3 is under another environment called conda. Your makefile worked well in it and the generated reference manuals looked fine.

**Comment by rfalgout** [comment]
Thanks @liruipeng for testing this out!  I have been wondering for some time now how to get other developers set up to write/build the new documentation.

**Pull request merged**
