### PR TITLE
Fix memory leak on BoomerAMG complex smoothers

### PR DESCRIPTION
**Pull request by victorapm**
Depends on #889 

This fixes an issue reported here: https://github.com/hypre-space/hypre/pull/889#issuecomment-1519055025

The memory leak was happening when:

1. A complex smoother for BoomerAMG was selected.
2. The AMG hierarchy consisted of one level.
3. The BoomerAMG preconditioner was destroyed and recomputed again.

I'm not sure how to add a situation like this one to our regression tests

### CODE REVIEW

**Comment by prj-** [comment]
Can confirm this fixes https://github.com/hypre-space/hypre/issues/764. Thanks!

**Comment by victorapm** [comment]
Thanks for confirming!!

**Review by ulrikeyang — APPROVED** [review]
This looks good to me. Thank you.

**Review by rfalgout — APPROVED** [review]
Looks good.  Thanks!

**Comment by prj-** [comment]
Could you please merge this as well Victor?

**Comment by victorapm** [comment]
Working on it right now

**Comment by prj-** [comment]
Great! And later on, it would be good to rebase `cuda12` as well. Lots of bug fixing 😅

**Comment by victorapm** [comment]
Yes! Rui Peng is waiting on a few reviews there. I'll update the `cuda12` branch wrt `master` in the meantime

**Pull request merged**
