### PR TITLE
superlu_dist support on GPUs

### PR DESCRIPTION
**Pull request by liruipeng**
This PR adds superlu_dist support on GPUs.

- [x] tux
- [x] lassen
- [x] tioga
- [x] sunspot

### CODE REVIEW

**Review by rfalgout — APPROVED** [review]
Looks good to me.  Should we add a GPU test as well, like what we do in `machine-tux-spack.sh` currently?  This might be a bit more complicated though.  Just thinking out loud.

**Comment by liruipeng** [comment]
> Looks good to me. Should we add a GPU test as well, like what we do in `machine-tux-spack.sh` currently? This might be a bit more complicated though. Just thinking out loud.

That will be great to have. I will work with @osborn9 on it. Thanks!

**Review by ulrikeyang — APPROVED** [review]
This looks good. Thanks.

**Review by osborn9 — APPROVED** [review]
I've been able to successfully run the ij driver using superlu-dist as coarse grid solver on Lassen. Nice work!! 

The outstanding issue (which I'm working on but don't have a complete solution yet) is adding a lassen-spack test to test with the most recent superlu-dist master. This can be added as a separate MR.

**Review by oseikuffuor1 — APPROVED** [review]
Changes look fine to me. Thanks Rui.

**Pull request merged**
