### PR TITLE
Amg setup

### PR DESCRIPTION
**Pull request by liruipeng**

### CODE REVIEW

**Review by rfalgout — APPROVED** [review]
These changes look fine to me.  Thanks!

**Comment by liruipeng** [comment]
@rfalgout I don't know what I did but did not want to request review from you again. Sorry.

**Review by rfalgout — APPROVED** [review]

**Review by ulrikeyang — APPROVED** [review]
This looks good. Thanks!

**Review by bjorn2 — APPROVED** [review]

**Comment by liruipeng** [comment]
@ulrikeyang @rfalgout @bjorn2 Merged. Thank you all

**Pull request merged**
