### PR TITLE
Gpu mixedInt

### PR DESCRIPTION
**Pull request by liruipeng**
This PR adds GPU support for mixedInt. Previous implementations did not consider difference between `HYPRE_Int` and `HYPRE_BigInt` in many places. This PR fixes by correcting the improper uses. Related, `--enable-bigint` feature on GPU is not yet supported.

### CODE REVIEW

**Comment by rfalgout** [comment]
Hi @liruipeng .  Can you provide some more context for what's going on here?  Why did the mixed-int port of hypre not work on GPUs and what (at a high level) is your solution approach here?  Thanks!

**Comment by liruipeng** [comment]
@rfalgout Sorry for the confusion. I added descriptions of this PR.

**Review by rfalgout — APPROVED** [review]
Looks good.  Thanks!

**Review by ulrikeyang — APPROVED** [review]
This looks fine. Thank you

**Comment by liruipeng** [comment]
Hi @oseikuffuor1 Can you take a look at this? Thanks!

**Review by oseikuffuor1 — APPROVED** [review]
Looks good to me. Thanks @liruipeng!

**Pull request merged**
