### PR TITLE
Update sanity checks of hypre_SeqVectorElmdivpy

### PR DESCRIPTION
**Pull request by victorapm**
This fixes the regression test failure reported in #703.

### CODE REVIEW

**Review by rfalgout — APPROVED** [review]
Looks good.

**Comment by liruipeng** [comment]
Thanks @victorapm. Can I ask where was the offending call of `hypre_SeqVectorElmdivpy` that violated the assumptions on the sizes?

**Comment by victorapm** [comment]
Hi Rui Peng,

Here's the stacktrace:
```
#0  hypre_SeqVectorElmdivpy (x=0x5555a1cdfa60, b=0x7fffffffcdd0, y=0x5555a1f03f30) at /home/victor/projects/hypre-master/src/seq_mv/vector.c:646
#1  0x000055555566e2d2 in hypre_ParVectorElmdivpy (x=0x5555a1cdfa20, b=0x7fffffffce00, y=0x5555a1e2e980) at par_vector.c:463
#2  0x0000555555616731 in hypre_BoomerAMGRelax7Jacobi (A=0x5555a1f0c540, f=0x5555a1f04820, cf_marker=0x0, relax_points=0, relax_weight=1, l1_norms=0x7fff5a1efa00, u=0x5555a1e2e980, Vtemp=0x5555a1cdfa20) at par_relax.c:1151
#3  0x000055555561345e in hypre_BoomerAMGRelax (A=0x5555a1f0c540, f=0x5555a1f04820, cf_marker=0x0, relax_type=7, relax_points=0, relax_weight=1, omega=1, l1_norms=0x7fff5a1efa00, u=0x5555a1e2e980, Vtemp=0x5555a1cdfa20, Ztemp=0x5555a1cdffe0) at par_relax.c:111
#4  0x00005555557200ad in hypre_ParCSRRelax (A=0x5555a1f0c540, f=0x5555a1f04820, relax_type=1, relax_times=1, l1_norms=0x7fff5a1efa00, relax_weight=1, omega=1, max_eig_est=0, min_eig_est=0, cheby_order=0, cheby_fraction=0, u=0x5555a1e2e980, v=0x5555a1cdfa20, z=0x5555a1cdffe0) at ams.c:52
#5  0x0000555555ab42ca in hypre_BoomerAMGAdditiveCycle (amg_vdata=0x5555a1e72930) at par_add_cycle.c:319
#6  0x00005555555c01a0 in hypre_BoomerAMGSolve (amg_vdata=0x5555a1e72930, A=0x5555a1edbe00, f=0x5555a1cde670, u=0x5555a1ce04a0) at par_amg_solve.c:258
#7  0x00005555555ac963 in HYPRE_BoomerAMGSolve (solver=0x5555a1e72930, A=0x5555a1edbe00, b=0x5555a1cde670, x=0x5555a1ce04a0) at HYPRE_parcsr_amg.c:65
#8  0x000055555559fdae in hypre_GMRESSolve (gmres_vdata=0x5555a1eead60, A=0x5555a1edbe00, b=0x5555a1e72030, x=0x5555a1cdee10) at gmres.c:540
#9  0x00005555555942a0 in HYPRE_GMRESSolve (solver=0x5555a1eead60, A=0x5555a1edbe00, b=0x5555a1e72030, x=0x5555a1cdee10) at HYPRE_gmres.c:50
#10 0x0000555555573747 in main (argc=19, argv=0x7fffffffde98) at ij.c:6501
```

The size of `Vtemp` is not updated when changing to another level at `hypre_BoomerAMGAdditiveCycle` as we do in `hypre_BoomerAMGCycle`, which triggered one of the sanity checks that I had added in `hypre_SeqVectorElmdivpy`. perhaps we can look at changing the size of `Vtemp` in the future...

**Comment by ulrikeyang** [comment]
The size of Vtemp should not be changed here, because we need the whole vector for the matvec. This is somewhat tricky memory management for the additive AMG to treat the complete cycle as a matvec.

**Comment by victorapm** [comment]
@ulrikeyang, are the changes in this PR causing any problems?

**Comment by ulrikeyang** [comment]
Possibly. I don't have the time right now to look at that in detail.

**Pull request merged**
