### PR TITLE
Tux regression test fixes for rhel9 system

### PR DESCRIPTION
**Pull request by rfalgout**
The RHEL9 upgrade resulted in compiler version changes, etc. that broke some of the regression tests.  Most of the changes are because of new compiler warnings and saved file differences.  There are still one or two things to fix, but this is mostly ready to merge.

### CODE REVIEW

**Review by victorapm — APPROVED** [review]
Thanks, Rob!

What are the mpi library and gcc versions being used in the new tuxbox?

**Comment by rfalgout** [comment]
> Thanks, Rob!
> 
> What are the mpi library and gcc versions being used in the new tuxbox?

gcc (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)

For MPI, I installed my own version of MPICH: 4.2.2

**Comment by victorapm** [comment]
Thanks, Rob! I will need to update gcc on my box after this :)

**Comment by rfalgout** [comment]
I am getting the following output from the `examples/ex12f` run:
```
Note: The following floating-point exceptions are signalling: IEEE_DENORMAL
```
I was unable to figure out exactly what is triggering it and I think we can probably ignore it anyway.  Any opinions on this?  If we just filter the message out, should that be done in `runtest.sh` or in a new `machine-tux.filters` file?

**Pull request merged**
