### PR TITLE
Krylov solvers support to vector with multiple components

### PR DESCRIPTION
**Pull request by victorapm**
Copied from #728. This PR enables the use of Krylov methods for solving linear systems with multi-component vectors. Regression tests have been added on `src/test/TEST_ij/vector.sh`. Additionally, `hypre_ParCSRDiagScaleVector` and `hypreDevice_DiagScaleVector` have been extended to work with multi-component vectors.

Regression tests:

- [x] Tux
- [x] Lassen
- [x] Jlse (SYCL)

### CODE REVIEW

**Review by rfalgout — APPROVED** [review]
Looks good to me.  Thanks!

**Review by waynemitchell — APPROVED** [review]
Looks good to me. Thanks, Victor!

**Review by ulrikeyang — APPROVED** [review]
This looks fine.

**Review by liruipeng — APPROVED** [review]
Looks good to me. Thanks @victorapm

**Pull request merged**
