### PR TITLE
Cusolver

### PR DESCRIPTION
**Pull request by liruipeng**
Copied from #647, which adds the option of using cuSolver (https://docs.nvidia.com/cuda/cusolver/index.html), a GPU accelerated library for decompositions and linear system solutions from NVIDIA. We need the reordering algorithms (like RCM and AMD) on GPUs from cuSolver for ILU.

### CODE REVIEW

**Comment by rfalgout** [comment]
What is cuSolver?  More description on this PR would be nice.  Thanks!

**Comment by liruipeng** [comment]
> What is cuSolver? More description on this PR would be nice. Thanks!

Sorry about that. I added some description.

**Review by rfalgout — APPROVED** [review]
Looks good.  Thanks for the description!

**Review by osborn9 — COMMENTED** [review]
I was able to use cmake with this option successfully. Minor change: Please add this option to be used in the CMake GUI, i.e., 
```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index d933c6fc2..f6e342fae 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -108,6 +108,7 @@ option(HYPRE_ENABLE_UNIFIED_MEMORY   "Use unified memory for allocating the memo
 # CUDA options
 option(HYPRE_ENABLE_CUDA_STREAMS     "Use CUDA streams" ON)
 option(HYPRE_ENABLE_CUSPARSE         "Use cuSPARSE" ON)
+option(HYPRE_ENABLE_CUSOLVER         "Use cuSOLVER" OFF)
 option(HYPRE_ENABLE_DEVICE_POOL      "Use device memory pool" OFF)
 option(HYPRE_ENABLE_CUBLAS           "Use cuBLAS" OFF)
 option(HYPRE_ENABLE_CURAND           "Use cuRAND" ON)
``` 
(I can make this change it it's easier)

**Comment by liruipeng** [comment]
> I was able to use cmake with this option successfully. Minor change: Please add this option to be used in the CMake GUI, i.e.,
> 
> ```
> diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
> index d933c6fc2..f6e342fae 100644
> --- a/src/CMakeLists.txt
> +++ b/src/CMakeLists.txt
> @@ -108,6 +108,7 @@ option(HYPRE_ENABLE_UNIFIED_MEMORY   "Use unified memory for allocating the memo
>  # CUDA options
>  option(HYPRE_ENABLE_CUDA_STREAMS     "Use CUDA streams" ON)
>  option(HYPRE_ENABLE_CUSPARSE         "Use cuSPARSE" ON)
> +option(HYPRE_ENABLE_CUSOLVER         "Use cuSOLVER" OFF)
>  option(HYPRE_ENABLE_DEVICE_POOL      "Use device memory pool" OFF)
>  option(HYPRE_ENABLE_CUBLAS           "Use cuBLAS" OFF)
>  option(HYPRE_ENABLE_CURAND           "Use cuRAND" ON)
> ```
> 
> (I can make this change it it's easier)

Fixed. Thank you!

**Review by osborn9 — APPROVED** [review]

**Pull request merged**
