### PR TITLE
use FindCUDAToolkit.cmake when available

### PR DESCRIPTION
**Pull request by ibaned**
This is more work towards using CUDA on Windows. It hasn't actually been fully tested on Windows but should handle static libraries in an OS-generic way instead of the previous code that uses Linux-specific library names.

### CODE REVIEW

**Comment by ibaned** [comment]
Update: with 3fa79f3 it has been tested on Windows with CUDA and the build succeeds

**Comment by osborn9** [comment]
Apologies for my delay on reviewing this @ibaned! For the functionality, this looks good! 

For the style, please indent using 2 spaces the body of `if (CMAKE_VERSION VERSION_LESS 3.17)` / `else`.

**Comment by ibaned** [comment]
Hi @osborn9 ! I definitely delayed this myself way longer! Sorry for it slipping through the cracks, let me know if there's anything else you'd like done. Thanks for reviewing.

**Comment by osborn9** [comment]
Thanks @ibaned for making the formatting changes!

**Review by osborn9 — APPROVED** [review]

**Pull request merged**
