### PR TITLE
Update `README.md`

### PR DESCRIPTION
**Pull request by victorapm**
- Add link to GitHub Wiki
- Update description in the `SUPPORT.md` file

### CODE REVIEW

**Comment by victorapm** [comment]
We actually might need to bring `SUPPORT.md` back. See https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/R7.md

**Comment by rfalgout** [comment]
> We actually might need to bring `SUPPORT.md` back. See https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/R7.md

Yes, we need to keep the file.  Let me make a few changes and see what you think.

**Comment by rfalgout** [comment]
Okay, let me know what you think.

**Comment by rfalgout** [comment]
Also, let's get a few additional opinions (reviewers) before merging, since this updates the first thing users see.

**Comment by victorapm** [comment]
Thanks, looks good to me!

**Review by rfalgout — APPROVED** [review]

**Review by rfalgout — APPROVED** [review]

**Review by liruipeng — APPROVED** [review]

**Review by osborn9 — APPROVED** [review]

**Review by ulrikeyang — APPROVED** [review]
Looks good.

**Review by waynemitchell — APPROVED** [review]

**Review by oseikuffuor1 — APPROVED** [review]

**Pull request merged**
