### PR TITLE
Recmat structmat

### PR DESCRIPTION
**Pull request by rfalgout**
This fixes some regression test issues with structmat and sstructmat.  It's difficult to explain what the problem was, but it had to do with calling BoxManAssemble more than once.  There is an effort in the code to minimize the calls to this routine, but it leads to rather confusing code.  I ultimately had to add an argument to hypre_StructMatmultSetup to tell it when it should and should not assemble the grid for the product matrix.  I still think there is a potential issue with this that we will have to work through in the future.

### CODE REVIEW

**Review by victorapm — APPROVED** [review]
Thanks, Rob! I agree the old code was a bit confusing regarding the boxmanager calls. This solution is good!

**Comment by rfalgout** [comment]
I also just pushed fixes for the single and longdouble tests.  We only needed to update the saved files.

**Comment by rfalgout** [comment]
I added a fix for the maxwell issues.  With all of these changes, the nightly regression tests should be clean.

**Review by waynemitchell — APPROVED** [review]
All changes look good to me. Thanks, Rob!

**Pull request merged**
