### PR TITLE
Thoroughly address #960

### PR DESCRIPTION
**Pull request by prj-**
See also: https://github.com/hypre-space/hypre/pull/896

### CODE REVIEW

**Comment by prj-** [comment]
I don't know why I never took the time to fix this @victorapm, but here you go (see referenced MR and/or issue for the current warnings I get without this patch).

**Review by victorapm — APPROVED** [review]
Looks great, thanks @prj-

**Comment by victorapm** [comment]
@rfalgout , Pierre fixed some compilation warnings like:
```
: warning #3012-D: a volatile destination type for a compound assignment expression is deprecated
              move_bucket->hopInfo &= ~(1U << move_new_free_dist);
```

Which happens when compiling with `-std=c++20`

**Review by rfalgout — APPROVED** [review]
Looks good.  Thanks!

**Comment by liruipeng** [comment]
What exactly is the problem? Is it `|=`, `&=`, etc, or `startBucket->hopInfo`? Thanks

**Comment by rfalgout** [comment]
> What exactly is the problem? Is it `|=`, `&=`, etc, or `startBucket->hopInfo`? Thanks

Here is something I found explaining the issue:

https://stackoverflow.com/questions/65528802/incrementing-a-volatile-in-c20-with-operations-on-volatile-being-deprecated

**Pull request merged**
