### PR TITLE
Replace hipcc option `--amdgpu-target` with `--offload-arch`

### PR DESCRIPTION
**Pull request by victorapm**
Solves #1026.

Tested with rocm 5.2 and newer (tioga)

### CODE REVIEW

**Comment by liruipeng** [comment]
Is it back compatible?

**Comment by victorapm** [comment]
Tested with rocm 5.2, which is the minimum we support now

**Comment by liruipeng** [comment]
> Tested with rocm 5.2, which is the minimum we support now

Do we state this somewhere? In the manual?

**Comment by victorapm** [comment]
I didn't find it either. We should add to the manual/Wiki...

Right now, 5.2 is what we test with machine-tioga and hypre doesn't compile with versions older than 5.2 (I tried).

I don't think we should support rocm older than 5.2

**Comment by liruipeng** [comment]
> I didn't find it either. We should add to the manual/Wiki...
> 
> Right now, 5.2 is what we test with machine-tioga and hypre doesn't compile with versions older than 5.2 (I tried).
> 
> I don't think we should support rocm older than 5.2

Agreed. I used to test 5.1 or even 5.0. Not sure if it's still worth it.

**Review by liruipeng — APPROVED** [review]

**Pull request merged**
