### PR TITLE
Recmat merge + device compilation

### PR DESCRIPTION
**Pull request by victorapm**
- Merge master into recmat
- Add matvec option to struct driver (solver_id = -1)
- Fix GPU compilation
- Code style updates

### CODE REVIEW

**Review by rfalgout — APPROVED** [review]
Looks good.  Thanks!

**Comment by waynemitchell** [comment]
I pushed some changes for some of the code that I wrote that had changes on recmat not accounted for here.

**Comment by victorapm** [comment]
Sorry for missing those and thanks for catching!

**Review by waynemitchell — APPROVED** [review]
Looks good to me now. Thanks for cleaning up the style on a bunch of my code!

**Comment by victorapm** [comment]
Thanks, Wayne!

**Pull request merged**
