### PR TITLE
Add `hypre_ceildiv`

### PR DESCRIPTION
**Pull request by victorapm**
Add a macro for computing division where the result is always rounded up to the nearest integer.

This fixes a bug in master for the case when the dividend is zero.

### CODE REVIEW

**Comment by rfalgout** [comment]
What are your assumptions about the arguments for this macro?  Integer?  Non-negative?

**Comment by victorapm** [comment]
I assume non-negative dividend and positive divisor. It works for integers (non-negative) and floating point numbers

**Comment by victorapm** [comment]
Hi Rob, do the assumptions above sounds good? Another idea would be creating a `static inline` function

**Comment by rfalgout** [comment]
The assumptions sound good, but you may want to add a comment in front of the macro that state them.  Also, this will only do a 'ceil' if the result is cast to an integer (either implicitly or explicitly).  Maybe you should do the cast in the macro (to HYPRE_Int, for example).

**Review by rfalgout — APPROVED** [review]

**Comment by victorapm** [comment]
Thanks, I'll add the comment about assumptions

It's better to do the cast outside as this might be used for BigInts as well.

Thanks!

**Comment by rfalgout** [comment]
Yes, I thought about the BigInt question, and that's a good point.  The reason I brought it up was because of the macro name.  You might also want to say something about casting in the comment.  If all the numbers are real, and the result is real, then a ceil isn't done.

**Comment by victorapm** [comment]
Yes, good points! I'll add something about casting to the comment. Thanks again!

**Pull request merged**
