### PR TITLE
Fixed int types discrepancies in MPI calls.

### PR DESCRIPTION
**Pull request by TotoGaz**
Related to https://github.com/GEOSX/GEOSX/issues/2174 where we use the `--enable-mixedint` option when building `hypre`.

I've also written comments where I think there may be something tricky, but I do not know how to fix (neither if it's a real issue).

@victorapm

### CODE REVIEW

**Comment by victorapm** [comment]
Thank you for your contribution and also for pointing out the TODO's. Very helpful! I'll take care of them

**Comment by TotoGaz** [comment]
Hello @victorapm I've worked a little on building some tooling using [`clang-tidy`](https://clang.llvm.org/extra/clang-tidy/Contributing.html).
I could get to the following code. I'm really a noob for this so it's surely terrible code, but it surely could be enhanced (it's only for `Bcast` for the moment).
And actually it's not very easy!
And it's surely buggy because there are a lot of cases to consider 🤣 
```c++
#include "HypreCheckMpiCallsCheck.h"
#include "clang/AST/ASTContext.h"
#include "clang/ASTMatchers/ASTMatchFinder.h"

using namespace clang::ast_matchers;

namespace clang {
namespace tidy {
namespace mpi {

void HypreCheckMpiCallsCheck::registerMatchers(MatchFinder *Finder) {
  Finder->addMatcher(callExpr(callee(
    functionDecl(hasName("hypre_MPI_Bcast"))),
    hasArgument(0, hasDescendant(declRefExpr().bind("arg0"))),
    hasArgument(2, hasDescendant(declRefExpr().bind("arg2")))
  ).bind("hypre_MPI_Bcast"), this);
}

void HypreCheckMpiCallsCheck::check(const MatchFinder::MatchResult &Result) {
  const CallExpr *callExpr = Result.Nodes.getNodeAs<CallExpr>("hypre_MPI_Bcast");
  const DeclRefExpr *a0 = Result.Nodes.getNodeAs<DeclRefExpr>("arg0");
  const DeclRefExpr *a2 = Result.Nodes.getNodeAs<DeclRefExpr>("arg2");

  // Something like "ompi_mpi_long_long_int" or "ompi_mpi_int">,
  // but this is MPI implementation dependant!
  const std::string ompiTypeInfo = a2->getNameInfo().getAsString();

  const QualType t0 = a0->getType();
  const QualType ct0 = t0.getCanonicalType();
  const uint64_t size0 = Result.Context->getTypeSize(ct0); // TODO Is there an issue if the type is a pointer?

  const bool sizeMismatch =
      (ompiTypeInfo == "ompi_mpi_long_long_int" and size0 != 64) or
      (ompiTypeInfo == "ompi_mpi_int" and size0 != 32);
  if (sizeMismatch) {
    diag(callExpr->getExprLoc(), "Some `hypre_MPI_Bcast` has size problems.");
  }
}

} // namespace mpi
} // namespace tidy
} // namespace clang
```

**Comment by victorapm** [comment]
Hi Thomas, this looks nice! Thanks for taking your time preparing this. I'll try to use it

**Comment by TotoGaz** [comment]
Hello @victorapm I now understand that I misused some patterns of `clang-tidy`.
I'll post a better implementation in the next few days.
However, I think there is some very powerful tooling to be built in order to enhance the development of `hypre` there!

**Comment by TotoGaz** [comment]
@victorapm I've updated the code with a better version (at least that better respects the `clang-tidy` pattern).
As a matter of fact, I do not have those false positives anymore, but I cannot tell what's the deep reason for that! 😉 
Please be cautious!

I'm sure this could be of great help to detect mismatches, wrong casts, etc...
There could a dedicated set of `hypre` checks in the repository and in the CI/CD.

You could have a look at the "provided" `cppcoreguidelines-narrowing-conversions` check as well!

**Comment by victorapm** [comment]
Thanks @TotoGaz I'll take a look!

**Comment by victorapm** [comment]
```
#include "HypreCheckMpiCallsCheck.h"
```

Can you send me this file?

**Comment by TotoGaz** [comment]
It is automatically generated when you build your own rule.
```c++
//===--- HypreCheckMpiCallsCheck.h - clang-tidy -----------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_CLANG_TOOLS_EXTRA_CLANG_TIDY_MPI_HYPRECHECKMPICALLSCHECK_H
#define LLVM_CLANG_TOOLS_EXTRA_CLANG_TIDY_MPI_HYPRECHECKMPICALLSCHECK_H

#include "../ClangTidyCheck.h"

namespace clang {
namespace tidy {
namespace mpi {

/// FIXME: Write a short description.
///
/// For the user-facing documentation see:
/// http://clang.llvm.org/extra/clang-tidy/checks/mpi/hypre-check-mpi-calls.html
class HypreCheckMpiCallsCheck : public ClangTidyCheck {
public:
  HypreCheckMpiCallsCheck(StringRef Name, ClangTidyContext *Context)
      : ClangTidyCheck(Name, Context) {}
  void registerMatchers(ast_matchers::MatchFinder *Finder) override;
  void check(const ast_matchers::MatchFinder::MatchResult &Result) override;
};

} // namespace mpi
} // namespace tidy
} // namespace clang

#endif // LLVM_CLANG_TOOLS_EXTRA_CLANG_TIDY_MPI_HYPRECHECKMPICALLSCHECK_H
```

**Comment by victorapm** [comment]
Thanks!

**Pull request merged**
