### PR TITLE
Release 2.30.0

### PR DESCRIPTION
**Pull request by rfalgout**
See issue #1001

### CODE REVIEW

**Review by victorapm — APPROVED** [review]
Thanks!

**Review by liruipeng — APPROVED** [review]
Looks good. Thanks!

**Review by ulrikeyang — APPROVED** [review]
This looks good. Thank you!

**Review by oseikuffuor1 — APPROVED** [review]
Looks good to me. Thanks.

**Review by osborn9 — APPROVED** [review]

**Comment by waynemitchell** [comment]
@rfalgout , I also added sycl support for triangular solves, which enables Gauss-Seidel and ILU solves on Intel GPUs if you want to add that to the CHANGELOG. Otherwise, looks good. I'm running the regression tests on Sunspot right now, but I don't foresee any issues.

**Review by waynemitchell — APPROVED** [review]

**Comment by rfalgout** [comment]
> @rfalgout , I also added sycl support for triangular solves, which enables Gauss-Seidel and ILU solves on Intel GPUs if you want to add that to the CHANGELOG. Otherwise, looks good. I'm running the regression tests on Sunspot right now, but I don't foresee any issues.

Good catch, Wayne!  Somehow I missed that log entry.  All fixed now.

Thanks for running the sunspot tests, too!

**Pull request merged**
