### PR TITLE
Add MGR statistics

### PR DESCRIPTION
**Pull request by victorapm**
This PR adds statistics info to MGR. An example for a 4-levels reduction strategy below:

```
 Num MPI tasks = 1
 Num OpenMP threads = 1


MGR SETUP PARAMETERS:

    MGR num levels = 5
    AMG num levels = 3
  Total num levels = 8

            Global           Fine           Coarse
lev     relaxation     relaxation      grid method    Interpolation      Restriction
====================================================================================
  0             --       User AMG       NG-BlkDiag         Diag Inv        Injection
  1     Blk-Jacobi      Dense Inv              RAP     Blk-Diag Inv        Injection
  2        BJ-ILU0         Jacobi              RAP         Diag Inv        Injection
  3         Blk-GS         Jacobi   NG-CPR-BlkDiag        Injection        Injection
  4     Blk-Jacobi         Jacobi               --               --               --



Full Operator Matrix Hierarchy Information:

                     nonzero   actual         |       entries/row        |              rowsums 
lev    rows    fine  entries  entries  sparse |  min  max     avg  stdev |      min      max      avg    stdev 
==============================================+==========================+=====================================
  0    2203     864    81704    81699  98.316 |    1  105    37.1  29.28 | -9.7e+11  8.9e+04 -5.6e+10  1.6e+11
  1    1339      16    68347    68342  96.188 |    1   87    51.0  30.86 | -9.7e+11  2.1e+05 -9.3e+10  2.0e+11
  2    1323     441    67960    67960  96.117 |    1   81    51.4  30.75 | -9.7e+11  1.8e-03 -9.4e+10  2.0e+11	( MGR )
  3     882     441   104304   104304  86.592 |    1  250   118.3  85.12 | -4.6e+11  1.3e-03 -1.0e+11  1.7e+11
  4     441     319    31431    26139  83.839 |    1  125    71.3  31.50 | -4.6e+11  9.0e-04 -1.0e+11  1.7e+11
----------------------------------------------+--------------------------+------------------------------------- MGR's coarsest level
  5     122      95     8514     8514  42.798 |   36  104    69.8  16.96 | -6.7e+11  4.5e+10 -2.1e+11  2.1e+11
  6      27      18      707      707   3.018 |   20   27    26.2   1.47 | -1.1e+12 -1.4e+11 -5.2e+11  2.3e+11	( AMG )
  7       9       9       81       81   0.000 |    9    9     9.0   0.00 | -1.3e+12 -3.1e+11 -7.7e+11  3.0e+11



Full Prolongation Matrix Hierarchy Information:

                       nonzero   actual         |       entries/row       |              rowsums 
lev    rows x cols     entries  entries  sparse |  min  max    avg  stdev |      min      max      avg    stdev 
================================================+=========================+=====================================
  0    2203 x 1339       15175    15175  99.687 |    0   27    6.9  10.20 | -7.5e-08  1.2e+02  6.9e-01  2.9e+00
  1    1339 x 1323        1707     1659  99.905 |    1   24    1.3   2.50 | -5.8e-11  1.0e+00  9.9e-01  1.1e-01
  2    1323 x 882        17488    17488  99.001 |    0   54   13.2  19.87 | -2.5e-16  1.0e+00  6.7e-01  4.7e-01	( MGR )
  3     882 x 441          441      441  99.943 |    0    1    0.5   0.50 |  0.0e+00  1.0e+00  5.0e-01  5.0e-01
------------------------------------------------+-------------------------+------------------------------------- MGR's coarsest level
  4     441 x 122          885      885  99.545 |    0    4    2.0   1.77 |  0.0e+00  1.2e+00  6.6e-01  4.4e-01
  5     122 x 27           386      386  97.407 |    1    4    3.2   1.27 |  3.0e-01  1.0e+00  7.6e-01  2.5e-01	( AMG )
  6      27 x 9             81       81  88.889 |    1    4    3.0   1.41 |  2.7e-01  1.0e+00  6.0e-01  2.9e-01


At MGR level 0 --> F-relaxation solver parameters

   Solver Type = BoomerAMG
   Strength Threshold = 0.800000
   Interpolation Truncation Factor = 0.000000
   Maximum Row Sum Threshold for Dependency Weakening = 1.000000
   Number of functions = 3
   Coarsening type = HMIS
   Prolongation type = extended+i
   Cycle type = V(1,1)

   
Operator Matrix Hierarchy Information:

                        nonzero   actual         |      entries/row       |              rowsums 
   lev    rows    fine  entries  entries  sparse |  min  max    avg stdev |      min      max      avg    stdev 
   ==============================================+========================+=====================================
     0     864     612     5915     5915  99.208 |    1   18    6.8  4.60 | -7.7e+01  8.9e+04  2.7e+04  3.1e+04
     1     252     156     2577     2573  95.942 |    1   28   10.2  6.01 |  6.2e-01  9.8e+04  3.2e+04  2.3e+04
     2      96      54     1373     1293  85.102 |    1   39   14.3  9.59 | -3.9e+00  9.8e+04  3.1e+04  2.2e+04
     3      42      28      658      565  62.698 |    3   34   15.7  8.17 |  1.1e+03  7.4e+04  2.5e+04  2.0e+04
     4      14       8      155      138  20.918 |    4   14   11.1  3.53 |  1.2e+00  7.3e+04  2.0e+04  2.4e+04
     5       6       6       34       30   5.556 |    5    6    5.7  0.47 |  3.0e+03  4.4e+04  1.8e+04  1.6e+04


   
Prolongation Matrix Hierarchy Information:

                          nonzero   actual         |     entries/row      |              rowsums 
   lev    rows x cols     entries  entries  sparse |  min  max   avg stdev |      min      max      avg    stdev 
   ================================================+======================+=====================================
     0     864 x 252          652      652  99.913 |    0    3   0.8 0.61 |  0.0e+00  1.0e+00  4.9e-01  5.0e-01
     1     252 x 96           326      326  99.487 |    0    4   1.3 0.87 |  0.0e+00  1.0e+00  6.6e-01  4.7e-01
     2      96 x 42           130      125  98.589 |    0    4   1.4 0.85 |  0.0e+00  1.0e+00  6.8e-01  4.7e-01
     3      42 x 14            59       51  96.655 |    1    4   1.4 0.79 |  8.9e-34  1.0e+00  6.5e-01  4.7e-01
     4      14 x 6             18       17  90.816 |    1    2   1.3 0.45 |  5.0e-17  1.0e+00  7.9e-01  3.6e-01


At MGR level 4 (Coarsest) --> Solver parameters:

   Solver Type = BoomerAMG
   Strength Threshold = 0.250000
   Interpolation Truncation Factor = 0.000000
   Maximum Row Sum Threshold for Dependency Weakening = 0.900000
   Number of functions = 1
   Coarsening type = HMIS
   Prolongation type = extended+i
   Cycle type = V(1,1)

MGR complexities:

 lev       grid   operator     memory 
=====================================
   0      1.475      1.811      1.804 
   1      1.000      1.000      1.000 
   2      1.000      1.000      1.000 
   3      1.000      1.000      1.000 
   4      1.365      1.296      1.293 
------------------------------------- 
 All      0.852      0.630      0.628 
------------------------------------- 
```

### CODE REVIEW

**Comment by rfalgout** [comment]
This looks good to me.  Does any of it impact the regression tests because of output format changes?

**Review by rfalgout — APPROVED** [review]
Thanks!

**Comment by victorapm** [comment]
Thanks, Rob! The new output contents did not impact the regression tests (we were just checking for number of iterations and residual norms)

**Review by oseikuffuor1 — APPROVED** [review]
Thanks Victor.

**Pull request merged**
