### PR TITLE
Add HYPRE_DEVELOP variables

### PR DESCRIPTION
**Pull request by rfalgout**
This PR adds the following two variables to `HYPRE_config.h` when there is a `.git` directory in the hypre source (they are otherwise left undefined)

    HYPRE_DEVELOP_STRING
    HYPRE_DEVELOP_NUMBER

The first is a string that comes from the `git describe` command that indicates the last release tag, the number of commits beyond that last release, and the corresponding commit hash.  The second is the number of commits since the last release.  For example,

    #define HYPRE_DEVELOP_STRING "v2.22.1-5-g667fb77ba"
    #define HYPRE_DEVELOP_NUMBER 5

These new variables may help users who work directly with the development branch of hypre to keep their code current and backward compatible with previous releases and also individual commits between those releases.

The idea came out of a recent issue with MFEM: https://github.com/mfem/mfem/pull/2458#issuecomment-899977877

The MFEM team does something similar here:  https://github.com/mfem/mfem/blob/9af03fc80b94ea82ce07938b12fdf3dc3466d56c/makefile#L119

Some notes:

- This is a first draft intended to generate discussion and improvements.
- I would like to invite people from MFEM, our code teams, and the xSDK to comment.
- I tried to make this as portable as possible by not depending too heavily on a shell.  It would be nice if this also worked with Windows, for example.

Some questions:

- Do we need a way to distinguish the development branch from other branches?  The above example resulted from running `configure` on this PR branch, NOT on master.  It would be possible to generate the same release string and commit number from an entirely different branch, and only the hash would differ.  I'm not sure this is really important, but I'd like to hear what others think.
- Do we want to generate a warning when the `.git` directory is not found?  That is the current behavior.
- This assumes that the `git` command is in the user's path and available.  Is it worth doing any additional checking here?

Some to-do items:

- [x] Write regression tests to ensure this continues to work.
- [x] Run regression tests

### CODE REVIEW

**Comment by rfalgout** [comment]
Hi @pazner @v-dobrev .  It would be nice to get your input on this PR.

**Review by victorapm — APPROVED** [review]
Hi @rfalgout, I think this is great and provides the necessary information to other packages be always up-to-date with API changes. I can see the new variables when configuring hypre downloaded via `git clone`.

My only comment is that we could add this information to our drivers. This would help reproducing results generated in the past when we aren't sure which version of the code was used. Something like:
```
#ifdef HYPRE_DEVELOP_STRING
   if (!myid)
   {
      hypre_printf("Using HYPRE_DEVELOP_STRING: %s\n", HYPRE_DEVELOP_STRING);
   }
#endif
```
Output example with `ij` driver:

```
Using HYPRE_DEVELOP_STRING: v2.22.1-5-g667fb77ba

Running with these driver parameters:
  solver ID    = 2

=============================================
Hypre init times:
=============================================
Hypre init:
  wall clock time = 0.000002 seconds
  wall MFLOPS     = 0.000000
  cpu clock time  = 0.000002 seconds
  cpu MFLOPS      = 0.000000

  Laplacian:   num_fun = 1
    (nx, ny, nz) = (10, 10, 10)
    (Px, Py, Pz) = (1, 1, 1)
    (cx, cy, cz) = (1.000000, 1.000000, 1.000000)

=============================================
Generate Matrix:
=============================================
Spatial Operator:
  wall clock time = 0.000088 seconds
  wall MFLOPS     = 0.000000
  cpu clock time  = 0.000089 seconds
  cpu MFLOPS      = 0.000000

  RHS vector has unit components
  Initial guess is 0
=============================================
IJ Vector Setup:
=============================================
RHS and Initial Guess:
  wall clock time = 0.000032 seconds
  wall MFLOPS     = 0.000000
  cpu clock time  = 0.000032 seconds
  cpu MFLOPS      = 0.000000

Solver: DS-PCG
HYPRE_ParCSRPCGGetPrecond got good precond
=============================================
Setup phase times:
=============================================
PCG Setup:
  wall clock time = 0.000024 seconds
  wall MFLOPS     = 0.000000
  cpu clock time  = 0.000023 seconds
  cpu MFLOPS      = 0.000000

Iterations = 23
Final Relative Residual Norm = 8.691352e-09
```

**Comment by rfalgout** [comment]
> My only comment is that we could add this information to our drivers. This would help reproducing results generated in the past when we aren't sure which version of the code was used. Something like:
> 
> Output example with `ij` driver:
> 
> ```
> Using HYPRE_DEVELOP_STRING: v2.22.1-5-g667fb77ba
> 

Excellent idea @victorapm !

**Comment by v-dobrev** [comment]
Hi @rfalgout,

This looks good to me.

One potential issue is if you decide to add an annotated tag that is not a release tag. It looks like `git describe` has the option `--match <pattern>` to restrict the tag name search pattern, if you want to leave the door open to the possibility of having non-release annotated tags.

**Comment by pazner** [comment]
Looks great to me, I think both Victor and Veselin's suggestions are good.

**Review by tzanio — APPROVED** [review]
Thanks for adding this @rfalgout !

**Review by ulrikeyang — APPROVED** [review]
This looks good. Thanks

**Comment by liruipeng** [comment]
> * Do we need a way to distinguish the development branch from other branches?  The above example resulted from running `configure` on this PR branch, NOT on master.  It would be possible to generate the same release string and commit number from an entirely different branch, and only the hash would differ.  I'm not sure this is really important, but I'd like to hear what others think.

I am not seeing why we need `branch` information (name?) in `HYPRE_DEVELOP_STRING`. I assume the hash, or the  "abbreviated object name" from `git describe` is unique even across branches.

> * Do we want to generate a warning when the `.git` directory is not found?  That is the current behavior.

If there is no `.git`, such as using a downloaded tar ball file from the release, is `HYPRE_DEVELOP_STRING` supposed to be just the release tag like `v2.22.1` (instead of undefined?), and never be changed?

> * This assumes that the `git` command is in the user's path and available.  Is it worth doing any additional checking here?

Checking is fine. But I don't have strong feelings.

P.S About my earlier concern about `HYPRE_DEVELOP_NUMBER`, which is the number of additional commits on top of the most recent tagged object, I think this is useful to have in addition to `HYPRE_DEVELOP_STRING`, e.g., when one wants to do some numerical comparisons for determining the version of hypre being used. The only risk to mess it up is if developers want to rewrite the history (there are some unfortunate situations online why people wanted to do that), which we should never do. For a broader community as xSDK, we should be careful if changing history never happens for all libraries, something to keep in mind.

This looks great. Thank you @rfalgout .

**Review by waynemitchell — APPROVED** [review]
Looks good to me. Thanks, Rob!

**Comment by rfalgout** [comment]
Thanks all for the comments and suggestions!

I added the `--match` idea from @v-dobrev .  This turned out to be a bit more complicated than I anticipated.  I wanted to use `--match 'v[0-9]*'` to more closely match our release tags, but autoconf can't handle the brackets without the use of something called [quadrigraphs ](https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Quadrigraphs.html).  That's too ugly for me to make it worthwhile.  Also, it turns out that you can't use the single quotes in the CMake `execute_process` command, but removing them was enough to get it to work.  It would be interesting to see what the CMake stuff does on a Windows box.

**Comment by rfalgout** [comment]
> If there is no `.git`, such as using a downloaded tar ball file from the release, is `HYPRE_DEVELOP_STRING` supposed to be just the release tag like `v2.22.1` (instead of undefined?), and never be changed?

Hi @liruipeng .  There is already a `HYPRE_RELEASE_VERSION` and `HYPRE_RELEASE_NUMBER` that serves this purpose well enough I think.  It doesn't give the exact git tag, but it provides enough information to figure that out, and presumably the user is not using git in the first place anyway.  So, I think it's better to leave the two `DEVELOP` variables undefined when there is no `.git` directory.

**Review by liruipeng — APPROVED** [review]

**Review by oseikuffuor1 — APPROVED** [review]
Thanks @rfalgout!

**Review by osborn9 — APPROVED** [review]
This looks good to me @rfalgout! Thanks!!

Apologies, but I unintentionally marked it "Ready for review" and don't know if I can undo that action.

**Comment by rfalgout** [comment]
> This looks good to me @rfalgout! Thanks!!
> 
> Apologies, but I unintentionally marked it "Ready for review" and don't know if I can undo that action.

Thanks, @osborn9 !  It was no problem to make this "draft" again.  BTW, are there people in the xSDK that you or @ulrikeyang think we should invite for comment?  If so, please feel free to reach out.

**Comment by chris-schroeder** [comment]
Good ideas. No objections. I've actually been doing something similar (getting the abbreviated commit hash for HYPRE and embedding it into a print statement in HYDRA) in my build script ever since I started using non-standard versions.

**Comment by rfalgout** [comment]
> Good ideas. No objections.

Thanks for taking a look, @chris-schroeder !

**Comment by rfalgout** [comment]
Hi All,

@solberg2 suggested we have a way of indicating if `HYPRE_DEVELOP_STRING` corresponds to the main development branch (or not).  This could be useful, so I added a new string called `HYPRE_DEVELOP_BRANCH` that is defined only if the main development branch is being used.  When defined, it is set to the name of the branch (currently `master`) just to provide more than a Boolean.  In the future, if we decide to change hypre's main development branch to something else, it should be trivial to update this feature.

Let me know if you have any comments or other suggestions.  Thanks!

**Comment by rfalgout** [comment]
Hello again,

I added a way to do some regression testing on these new variables in:

    src/test/TEST_struct/versioncheck.jobs
    src/test/TEST_struct/versioncheck.sh

Doing it this way has several advantages:

- It will run on most of the platforms we test without changing anything in `AUTOTEST`
- It will work whether we use autoconf or cmake to build the code
- It separately implements the logic in the autoconf and cmake build systems
- It will let us know if we pull new source and forget to rebuild before running tests manually (discovered that by accident)
- It ensures that we continue to print the version information in our drivers

Disadvantages:

- It only works on linux-based systems
- It uses `git`, which might be a problem on machines with separate build/run environments (?)

Let me know what you think.  If this looks good, then I will add similar tests to `TEST_ij` and `TEST_sstruct` and start running regression tests on different platforms.

Thanks!

**Comment by victorapm** [comment]
I think the new feature and test look great, Rob! Thanks!

**Pull request merged**
