### PR TITLE
Expose the AMS solver structure to users by including `ams.h` in `_hypre_parcsr_ls.h`

### LINKED ISSUE #667: Include contents of ams.h in _hypre_parcsr_ls.h
I'd like to modify the build process so that the contents of `ams.h` get added to `_hypre_parcsr_ls.h` (just as `par_amg.h`) appears got be copied over. My real goal is to be able to read properties of the AMS solver (either through the macros like `hypre_AMSDataDimension` or just by direct accessing the fields of the struct). An alternative would be to write proper `HYPRE_AMSGet*` functions (like those that exist for BoomerAMG).

Would a Hypre dev be able to help me with the build system changes? Or in adding the `HYPRE_AMSGet*` functions?

Thanks,
Tucker Babcock

### PR DESCRIPTION
**Pull request by tzanio**
Resolves #667

### CODE REVIEW

**Review by victorapm — APPROVED** [review]
Thanks for adding the macros.

**Comment by liruipeng** [comment]
@tzanio You may have forgotten to run `headers` to update `_hypre_parcsr_ls.h` (?). Thanks!

**Comment by tzanio** [comment]
> @tzanio You may have forgotten to run `headers` to update `_hypre_parcsr_ls.h` (?). Thanks!

Done

**Comment by liruipeng** [comment]
Now that `ams.h` is included in `_hypre_parcsr_ls.h`, shall we remove `#include "ams.h"` in the `.c` files?

**Comment by tzanio** [comment]
> Now that ams.h is included in _hypre_parcsr_ls.h, shall we remove #include "ams.h" in the .c files?

I don't have preference. Probably best to be consistent with AMG.

**Comment by tzanio** [comment]
FYI, this will be used in https://github.com/mfem/mfem/pull/3096

**Comment by tzanio** [comment]
Is there a timeline for merging this?

**Review by rfalgout — APPROVED** [review]
This looks good to me if everything still runs cleanly.

**Review by liruipeng — APPROVED** [review]
Looks good. Thanks @tzanio

**Comment by tzanio** [comment]
Thanks!

**Pull request merged**
