### PR TITLE
Add MAGMA support

### PR DESCRIPTION
**Pull request by victorapm**
This PR adds MAGMA support to both building systems (autotools and CMake) in hypre. For now, the main use case of MAGMA is to provide access to batched linear solvers for GPUs.

### CODE REVIEW

**Review by rfalgout — APPROVED** [review]
Looks good, Victor.  Thanks!

**Comment by victorapm** [comment]
@osborn9 @liruipeng @ulrikeyang This is updated with master now

**Review by osborn9 — APPROVED** [review]
I've tested with both Autoconf and CMake. Looks good! Thanks!

**Review by ulrikeyang — APPROVED** [review]
This looks good. Thank you

**Review by liruipeng — APPROVED** [review]

**Pull request merged**
