### PR TITLE
AMD ILU Support (WIP)

### PR DESCRIPTION
**Pull request by PaulMullowney**
Jacobi iterations with API for CPU ILU solver. GPU jacobi iterative solve now works with any ilu factorization choices.

Added GPU implementation of Matrix Row/Column permutation (should work for CUDA and HIP).

Added in hooks for cusolver (used for RCM reordering)

When iterative tri solve is chosen, one doesn't need to call solve analysis for the L and U factors.

Added Lower/Upper Jacobi iteration parameters for more flexibility.

Schur compliment iterative triangular solver works

AMD and Nvidia architectures work for block ILU0

Block Jacobi ILU0 and Block Jacobi ILU0 with Schur Compliment solvers work on summit and crusher without uvm.

### CODE REVIEW

**Comment by PaulMullowney** [comment]
@victorapm Any of my code with CuSolver can be discarded ... unless you want to keep it around. I didn't see any performance advantages with their reordering algorithms.

**Comment by victorapm** [comment]
@PaulMullowney Thanks for the update! I will keep this in mind while doing the merge

**Comment by PaulMullowney** [comment]
Would it be helpful if I pushed my current attempt at a rebase to a branch and we work from there? I have it down to 2 files where the diffs need to be resolved. par_ilu.c and par_ilu_setup.c

**Comment by victorapm** [comment]
Hi Paul, thanks for offering! So far, I managed to solve all the conflicts except for the two files you mentioned :) So, I guess we are at the same state

**Comment by victorapm** [comment]
@PaulMullowney I solved the conflicts and this is the new branch: https://github.com/hypre-space/hypre/tree/ilu-amd 

I will work on a few points and after they are done, I will open a PR to merge these changes into master. Thanks a lot for the contribution!

**Comment by PaulMullowney** [comment]
Excellent! I'll test this branch to make sure things compile and run properly. 

Are there significant issues with the implementation?

**Comment by victorapm** [comment]
Thanks, Paul!! There are no issues with the implementation. I will just need to do some refactoring and update style. Let me know if you find any problems with the `ilu-amd` branch :)

**Comment by PaulMullowney** [comment]
I built and ran one of my examples. It seg faults when I choose tri_solve=1 near the beginning of a GMRES iteration, but successfully converges when tri_solve=0. The difference in these paths is the former uses rocsparse triangular solve (and analysis). The latter uses a power series approximation to triangular solve and thus doesn't need analysis. There is likely something amiss in the solve analysis or related code.

**Comment by PaulMullowney** [comment]
I built and ran of my examples. It seg faults when I choose tri_solve=1, but successfully converges when tri_solve=0. The difference in these paths is the former using rocsparse triangular solve (and analysis). The latter uses a power series approximation to triangular solve. There is likely something amiss in the solve analysis or related data code.

**Comment by victorapm** [comment]
Thanks for the feedback! Is there a way to run your example through the `ij` driver? I can investigate

**Comment by PaulMullowney** [comment]
> Thanks for the feedback! Is there a way to run your example through the `ij` driver? I can investigate

Not easily. I'll try to track this down myself.

**Pull request closed without merging**
