### PR TITLE
Fix GPU build error and warnings

### PR DESCRIPTION
**Pull request by victorapm**
This PR contains fixes for hypre's GPU build. More precisely:

- Fix build error with cuda-12.5 due to the lack of using `thrust` namespace in a few places.
- Add definition to disable deprecated warnings from cuSPARSE-12 involving usage of ILU functions.
- Fix several warnings related to the CUDA build, most of them due to unused variables.
- Rename a few Cuda prefixed functions to a more generic name since they make sense for all GPU backends.

### CODE REVIEW

**Review by rfalgout — APPROVED** [review]
Looks good to me.  Thanks!

**Review by liruipeng — APPROVED** [review]
Looks good. Thanks!

**Comment by waynemitchell** [comment]
@victorapm , there are some issues here for the sycl build. Let me take a closer look, and I may push some chages.

**Comment by victorapm** [comment]
Thanks Wayne!

**Comment by waynemitchell** [comment]
Looks like the issue wasn't actually sycl-related. I think there was just one call to hypre_SyncComputeStream() that didn't get updated and still had the handle arg. So the compile failed. I went ahead and merged the most recent master and fixed that one function call. Running the sycl regressions now.

**Comment by waynemitchell** [comment]
Out of curiosity, what's the strategy behind using `HYPRE_UNUSED_VAR` vs. just removing the unused variable from the function? I guess that actually removing the unused variables is probably more changes/effort. But is there any other reason?

**Comment by liruipeng** [comment]
> Out of curiosity, what's the strategy behind using `HYPRE_UNUSED_VAR` vs. just removing the unused variable from the function? I guess that actually removing the unused variables is probably more changes/effort. But is there any other reason?

Sometimes where we have #ifdef, variables are not used in some branch but used in others. We can probably refactor the code but the HYPRE_UNUSED_VAR approach is probably easier. Just to silence compilers.

**Review by waynemitchell — APPROVED** [review]

**Comment by victorapm** [comment]
Just adding to Rui Peng's response, that is particularly true with `#if defined HYPRE_USING_GPU`. While, in other places such as BoomerAMG functions, refactoring would be easier to do.

**Pull request merged**
